/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //短语
    '			A\n		': '			成就\n		',
    '			D\n		': '			死亡\n		',
    '			V\n		': '			病毒\n		',
    '			I\n		': '			传染\n		',
    '			R\n		': '			复制\n		',
    '			S\n		': '			症状\n		',
    '			ST\n		': '			统计\n		',
    '			IN\n		': '			感染者\n		',
    '			U\n		': '			脱壳\n		',
    '			F\n		': '			致死性\n		',
    'virus points': '病毒点数',
    'Currently': '当前',
    'Keep Going': '继续',
    'infectivity': '传染',
    '15 total infectivity': '15总传染',
    '2,000 total infectivity': '2,000总传染',
    '\(softcapped': '(已达软上限',
    'replicators': '复制',
    '5 replicators': '5复制',
    '12 replicators': '12复制',
    'Reset for \+': '重置获得+',
    'uncoaters': '脱壳者',
    'ON': '开',
    'OFF': '关',
    'Completed': '已完成',
    '				Goal:': '				目标:',
    '				Reward': '				奖励',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    
    //长句
    'Gain 0.1 cases\/s.': '获得0.1病例/秒',
    'Your best virus points is ee': '你的最高病毒点数为ee',
    'Your best virus points is e': '你的最高病毒点数为e',
    'Your best virus points is': '你的最高病毒点数为',
    'Multiply cases gain.': '病例获取加成',
    'Multiplier to cases based on VP.': '基于病毒点数加成病例获取',
    'Multiplier to VP based on VP.': '基于病毒点数加成病毒点数获取',
    'Multiplier to cases based on cases.': '基于病例加成病例获取',
    'Multiplier to VP based on cases.': '基于病例加成病毒点数获取',
    'Raise \'Infection\' to the number of bought upgrades.': '基于已购买升级数加成"感染"',
    '\'Self Boost\' is stronger based on VP.': '基于病毒点数加成"自身加成"',
    '\'Contaminate\' is stronger based on cases.': '基于病例加成"污染"',
    'which boost cases gain by': '加成你的病例获取',
    'Your best infectivity is ee': '你的最高传染为ee',
    'Your best infectivity is e': '你的最高传染为e',
    'Your best infectivity is': '你的最高传染为',
    'Keep virus upgrades on reset.': '重置时保留病毒升级',
    'Gain 100% of VP gain per second.': '每秒获得100%重置可以获得的病毒点数',
    'Infectivity boosts VP gain.': '基于传染加成病毒点数',
    'Infectivity boosts \'Transmission\'.': '基于传染加成"传播"',
    'Multiplier to infectivity based on VP.': '基于病毒点数加成传染',
    'Infectivity increases \'Infection\' base.': '基于传染加成"感染"基础',
    'Cases increase \'Infection\' base.': '基于病例加成"感染"基础',
    'Multiplier to infectivity based on cases.': '基于病例加成传染',
    '\'Susceptible\' is stronger based on replicators and make it add and multiply.': '复制加成"易感"且同时加和乘',
    '\'Drug Resistance\' is stronger based on replicators and make it add and multiply.': '复制加成"药物抗性"且同时加和乘',
    '\'Resistance\' and \'Environmental Hardening\' is stronger based on infectivity.': '基于复制加成"抗性"和"环境强化"',
    'and increasing \'Infection\' base by': '并加成"感染"基础',
    'Your best replicators is e': '你的最高复制是e',
    'Your best replicators is': '你的最高复制是',
    'Infectivity boosts replicators 1st effect base.': '基于传染加成复制的第一个效果',
    'Replicators boost \'Disease\'.': '基于复制加成"疾病"',
    'VP boosts replicators 1st effect base.': '基于病毒点数加成复制的第一个效果',
    'VP boosts replicators 2nd effect.': '基于病毒点数加成复制的第二个效果',
    'Cases boost \'More Infections\'.': '基于病例加成"更多感染"',
    '\'Self Boost\' is stronger based on replicators': '基于复制加成“自身加成”',
    '\'Contaminate\' is stronger based on replicators': '基于复制加成"污染"',
    'Unlock a row of infectivity upgrades.': '解锁一排传染升级',
    '\'DNA\' is stronger based on cases': '基于病例加成"DNA"',
    'You can buy max replicators.': '购买复制可以购买最大',
    'which boost cases and infectivity by': '可以加成病例和传染',
    ', and boosts \'Uncoating\' by': ',且加成"脱壳"',
    'Your best uncoaters is e': '你的最高脱壳者为e',
    'Your best uncoaters is': '你的最高脱壳者为',
    'Best uncoaters boosts \'Infection\' base.': '基于最高脱壳者加成"感染"',
    '\'Transmission\' softcap starts later based on uncoaters and replicators.': '基于脱壳者和复制延缓"传播"软上限',
    'Uncoaters and replicators boost each other .': '脱壳者和复制互加',
    'Cases make replicators cheaper.': '基于病例降低复制价格',
    'Remove \'Air Transmission\' hardcap and its softcap starts later based on cases.': '移除"空气传播"硬上限，基于病例延缓它的软上限',
    'Infectivity boosts replicators 2nd effect.': '基于传染加成复制的第二个效果',
    'Infectivity boosts uncoaters 2nd effect.': '基于传染加成脱壳者的第二个效果',
    '\'Transcription\' is stronger based on uncoaters.': '基于脱壳者加成"转录"',
    'Keep Infectivity\/Replicator milestones on reset.': '重置保留传染/复制里程碑',
    'Gain 100% of infectivity gain per second.': '每秒获得重置可获得100%传染',
    'Keep Infectivity\/Replicator upgrades on reset.': '重置保留传染/复制升级',
    'Autobuy replicators.': '自动购买复制',
    'Replicators reset nothing.': '复制不再重置任何东西',
    'Unlock uncoater challenges.': '解锁脱壳者挑战',
    'Uncoaters are useless.': '脱壳者没有效果',
    'Uncoaters are useless. \(Completed': '脱壳者没有效果(已完成',
    'Infectivity and \'Infection\' are useless.': '传染和"感染"没有效果',
    'Infectivity and \'Infection\' are useless. \(Completed': '传染和"感染"没有效果(已完成',
    'Replicators are useless.': '复制没有效果',
    'Replicators are useless. \(Completed': '复制没有效果(已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4\) \(Completed': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4)(已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-',
    'Cases boost \'Genetic ReShuffle\'.': '基于病例加成"基因重组"',
    'Infectivity makes uncoaters cheaper.': '基于传染降低脱壳者价格',
    'Cases boost replicators 1st effect base.': '基于病例加成复制的第一个加成',
    'VP boosts \'Transcription\' and makes \'Transmission\' softcap weaker.': '基于病毒点数加成"感染"且使"感染"的软上限更弱',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    
    //标题
    'Start': '开始',
    'Infection': '感染',
    'Transmission': '传播',
    'Self Boost': '自身加成',
    'Contaminate': '污染',
    'More Infections': '更多感染',
    'Disease': '疾病',
    'BOOSTER': '加成者',
    'Food Contamination': '污染食物',
    'VP Boost': '病毒点数加成',
    'Air Transmission': '空气传播',
    'Resistance': '抗性',
    'Susceptible': '易感',
    'Drug Resistance': '药物抗性',
    'Environmental Hardening': '环境强化',
    'SUSceptible': '极易感',
    'Genetic Hardening': '基因强化',
    'Genetic ReShuffle': '基因重组',
    'Replication': '复制',
    'DNA': 'DNA',
    'Attachment': '拥护',
    'Entry': '参与',
    'Uncoating': '脱壳',
    'Transcription': '转录',
    'Synthesis': '合成',
    'Virion': '病毒体',
    'Release': '释放',
    'Main': '主界面',
    'Milestones': '里程碑',
    'Challenges': '挑战',
    'Uncoated Infection': '脱壳感染',
    'Water Transmission': '水源传播',
    'Synergy': '协同',
    'Genome Replication': '基因组复制',
    'Bird Transmission': '鸟类传播',
    'Viral Proteins': '病毒蛋白',
    'Viral Enzymes': '病毒酶',
    'Endocytosis': '内吞作用',
    'Coated': '已脱壳',
    'Disinfectant': '无法传染',
    'Unreplicated': '无法复制',
    'Masks': '口罩',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    'Current endgame: e3.689e12 mRNA \(v0.': '当前游戏终点：e3.689e12mRNA (v0.',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(\d+) uncoaters$/, '$1 脱壳者'],
    [/^Completed:(\d+)\/$/, '已完成:$1/'],
    [/^Cost: (.+) virus points\n			$/, '消耗：$1病毒点数'],
    [/^Cost: (.+) replicators\n			$/, '消耗：$1复制'],
    [/^Cost: (.+) infectivity\n			$/, '消耗：$1传染'],
    [/^Cost: (.+) uncoaters\n			$/, '消耗：$1脱壳者'],
    [/^(.+)\/sec$/, '$1/秒'],
    [/^\^(.+) \(softcapped$/, '^$1 (已达软上限'],
    [/^(.+)x \(softcapped$/, '$1x (已达软上限'],
    [/^Last save was (.+)s ago.$/, '上次保存在$1秒之前'],
    [/^You have (.+) cases$/, '你有$1病例'],
    [/^You have (.+) infectivity$/, '你有$1传染'],
    [/^You have made a total of (.+) virus points$/, '你总共获得了$1病毒点数'],
    [/^You have made a total of (.+) infectivity$/, '你总共获得了$1传染'],
    [/^You have made a total of (.+) replicators$/, '你总共获得了$1复制'],
    [/^You have made a total of (.+) uncoaters$/, '你总共获得了$1脱壳者'],
    [/^Last save was (.+)s ago. Average TPS = (.+)s\/tick.$/, '上次保存在$1秒之前，平均速度=$2秒/刻'],
    [/^(.+) \/ (.+) cases		\n		$/, '$1/$2病例		\n		'],
    [/^(.+) \/ (.+) infectivity		\n		$/, '$1/$2传染		\n		'],
    [/^(.+)x to replicators base, (.+)x to uncoaters base.$/, '$1×复制,$2×脱壳者'],

]);