/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //短语
    '			A\n		': '			成就\n		',
    '			D\n		': '			死亡\n		',
    '			V\n		': '			病毒\n		',
    '			I\n		': '			传染\n		',
    '			R\n		': '			复制\n		',
    '			S\n		': '			症状\n		',
    '			ST\n		': '			统计\n		',
    '			IN\n		': '			感染者\n		',
    '			U\n		': '			脱壳\n		',
    '			F\n		': '			致死性\n		',
    'virus points': '病毒点数',
    'Currently': '当前',
    'Keep Going': '继续',
    'infectivity': '传染',
    '15 total infectivity': '15总传染',
    '2,000 total infectivity': '2,000总传染',
    '\(softcapped': '(已达软上限',
    'replicators': '复制',
    '5 replicators': '5复制',
    '12 replicators': '12复制',
    'Reset for \+': '重置获得+',
    'uncoaters': '脱壳者',
    'ON': '开',
    'OFF': '关',
    'Completed': '已完成',
    '				Goal:': '				目标:',
    '				Reward': '				奖励',
    'symptoms': '症状',
    'deaths': '死亡',
    'fatality': '致死性',
    'Achievements': '成就',
    'Achievement Points': '成就点',
    'Atomic Virus': '原子病毒',
    'Auto': '自动',
    'Automated': '自动化',
    'Automatic Diseases': '自动化疾病',
    'Infect': '感染',
    'Thousand Infected': '千人感染',
    'Million Infected': '百万感染',
    'Covid': '冠状病毒',
    'World Infected': '世界级感染',
    'Infected infections': '传染性感染',
    'Upgraded infections': '感染升级',
    'Replicated': '复制',
    'Infected company': '感染工厂',
    'SUS Upgrade': '极易感升级',
    'Uncoated': '脱壳',
    'softcapped': '已达软上限',
    'hardcapped': '已达硬上限',
    'Challenging': '挑战中',
    'Infinite infections': '无限感染',
    'Severe case': '严重病例',
    'Dead': '死',
    'Corona Death': '死亡日冕',
    'Coffin': '棺材',
    'Coffin Dance': '棺材之舞',
    'Coughin Dance': '咳嗽之舞',
    'Mortal Kombat': '致命格斗',
    'Kortal Mombat': '斗格命致',
    'DIMENSIONS\?\?': '维度??',
    'NG\+\+\+ INFECTED': 'NG+++感染',
    'PPOOWWEERR!': '力！量！',
    'The 9th Dimension is a lie': '第九维度是个谎言',
    'Casual': '受害',
    'Fatally Challenged': '致命的挑战',
    'Zero Deaths': '零死亡',
    'REPLICANTI': '反复制',
    '\'ZERO\' Deaths': '"零"死亡',
    '0 cases from Casualty': '受害者0病例',
    'GoogolPlex': '古戈尔',
    'When will it be enough\?': '什么时候才够?',
    'Corona GAS': '日冕GAS',
    'Infected Challenge': '感染挑战',
    'Unimmune': '非免疫',
    'Diseased Diseases': '病态疾病',
    'Quarantined': '隔离',
    'E\-World Quarantine': '全世界隔离',
    'Unquarantined Quarantine': '反防疫防疫',
    'Multi\-Million': '百万倍增',
    'Cased GAS': '病例级GAS',
    'Molecular Virus': '分子病毒',
    'Phospate': '磷酸酯',
    'Phospate Virus': '磷酸酯病毒',
    'mRNA Virus': 'mRNA病毒',
    'Corona GAS GAS': '日冕GAS GAS',
    'Mutated': '突变',
    'Infecterrr': '感感感染',
    'In\'F\'ected': '感F染',
    'Mutated Mutations': '突变型突变',
    'fatality power': '致死性力量',
    'Max All \(M': '购买最大(M',
    'Fatality Dimension': '致死性维度',
    'Fatality Dimension Boost': '致死性维度加成',
    'Fatality Dimension Multiplier': '致死性维度倍增器',
    'Social Distant Multiplier Boost': '远距离倍增器加成',
    'casualty': '受害者',
    'casualty per second.': '受害者每秒',
    'casual viruses': '受害病毒',
    'infecters': '感染者',
    'Respec Infections': '重置感染',
    'total': '总共',
    'infected infections \(': '传染感染 (',
    'Exit Early': '提前退出',
    'Finish': '完成',
    '': '',
    '': '',
    '': '',
    
    //长句
    'Gain 0.1 cases\/s.': '获得0.1病例/秒',
    'Your best virus points is ee': '你的最高病毒点数为ee',
    'Your best virus points is e': '你的最高病毒点数为e',
    'Your best virus points is': '你的最高病毒点数为',
    'Multiply cases gain.': '病例获取加成',
    'Multiplier to cases based on VP.': '基于病毒点数加成病例获取',
    'Multiplier to VP based on VP.': '基于病毒点数加成病毒点数获取',
    'Multiplier to cases based on cases.': '基于病例加成病例获取',
    'Multiplier to VP based on cases.': '基于病例加成病毒点数获取',
    'Raise \'Infection\' to the number of bought upgrades.': '基于已购买升级数加成"感染"',
    '\'Self Boost\' is stronger based on VP.': '基于病毒点数加成"自身加成"',
    '\'Contaminate\' is stronger based on cases.': '基于病例加成"污染"',
    'which boost cases gain by': '加成你的病例获取',
    'Your best infectivity is ee': '你的最高传染为ee',
    'Your best infectivity is e': '你的最高传染为e',
    'Your best infectivity is': '你的最高传染为',
    'Keep virus upgrades on reset.': '重置时保留病毒升级',
    'Gain 100% of VP gain per second.': '每秒获得100%重置可以获得的病毒点数',
    'Infectivity boosts VP gain.': '基于传染加成病毒点数',
    'Infectivity boosts \'Transmission\'.': '基于传染加成"传播"',
    'Multiplier to infectivity based on VP.': '基于病毒点数加成传染',
    'Infectivity increases \'Infection\' base.': '基于传染加成"感染"基础',
    'Cases increase \'Infection\' base.': '基于病例加成"感染"基础',
    'Multiplier to infectivity based on cases.': '基于病例加成传染',
    '\'Susceptible\' is stronger based on replicators and make it add and multiply.': '复制加成"易感"且同时加和乘',
    '\'Drug Resistance\' is stronger based on replicators and make it add and multiply.': '复制加成"药物抗性"且同时加和乘',
    '\'Resistance\' and \'Environmental Hardening\' is stronger based on infectivity.': '基于复制加成"抗性"和"环境强化"',
    'and increasing \'Infection\' base by': '并加成"感染"基础',
    'Your best replicators is e': '你的最高复制是e',
    'Your best replicators is': '你的最高复制是',
    'Infectivity boosts replicators 1st effect base.': '基于传染加成复制的第一个效果',
    'Replicators boost \'Disease\'.': '基于复制加成"疾病"',
    'VP boosts replicators 1st effect base.': '基于病毒点数加成复制的第一个效果',
    'VP boosts replicators 2nd effect.': '基于病毒点数加成复制的第二个效果',
    'Cases boost \'More Infections\'.': '基于病例加成"更多感染"',
    '\'Self Boost\' is stronger based on replicators': '基于复制加成“自身加成”',
    '\'Contaminate\' is stronger based on replicators': '基于复制加成"污染"',
    'Unlock a row of infectivity upgrades.': '解锁一排传染升级',
    '\'DNA\' is stronger based on cases': '基于病例加成"DNA"',
    'You can buy max replicators.': '购买复制可以购买最大',
    'which boost cases and infectivity by': '可以加成病例和传染',
    ', and boosts \'Uncoating\' by': ',且加成"脱壳"',
    'Your best uncoaters is e': '你的最高脱壳者为e',
    'Your best uncoaters is': '你的最高脱壳者为',
    'Best uncoaters boosts \'Infection\' base.': '基于最高脱壳者加成"感染"',
    '\'Transmission\' softcap starts later based on uncoaters and replicators.': '基于脱壳者和复制延缓"传播"软上限',
    'Uncoaters and replicators boost each other .': '脱壳者和复制互加',
    'Cases make replicators cheaper.': '基于病例降低复制价格',
    'Remove \'Air Transmission\' hardcap and its softcap starts later based on cases.': '移除"空气传播"硬上限，基于病例延缓它的软上限',
    'Infectivity boosts replicators 2nd effect.': '基于传染加成复制的第二个效果',
    'Infectivity boosts uncoaters 2nd effect.': '基于传染加成脱壳者的第二个效果',
    '\'Transcription\' is stronger based on uncoaters.': '基于脱壳者加成"转录"',
    'Keep Infectivity\/Replicator milestones on reset.': '重置保留传染/复制里程碑',
    'Gain 100% of infectivity gain per second.': '每秒获得重置可获得100%传染',
    'Keep Infectivity\/Replicator upgrades on reset.': '重置保留传染/复制升级',
    'Autobuy replicators.': '自动购买复制',
    'Replicators reset nothing.': '复制不再重置任何东西',
    'Unlock uncoater challenges.': '解锁脱壳者挑战',
    'Uncoaters are useless.': '脱壳者没有效果',
    'Uncoaters are useless. \(Completed': '脱壳者没有效果(已完成',
    'Uncoaters are useless. \(In Challenge': '脱壳者没有效果(挑战中',
    'Uncoaters are useless. \(In Challenge\) \(Completed': '脱壳者没有效果(挑战中) (已完成',
    'Infectivity and \'Infection\' are useless.': '传染和"感染"没有效果',
    'Infectivity and \'Infection\' are useless. \(Completed': '传染和"感染"没有效果(已完成',
    'Infectivity and \'Infection\' are useless. \(In Challenge': '传染和"感染"没有效果(挑战中',
    'Infectivity and \'Infection\' are useless. \(In Challenge\) \(Completed': '传染和"感染"没有效果(挑战中) (已完成',
    'Replicators are useless.': '复制没有效果',
    'Replicators are useless. \(Completed': '复制没有效果(已完成',
    'Replicators are useless. \(In Challenge': '复制没有效果(挑战中',
    'Replicators are useless. \(In Challenge\) \(Completed': '复制没有效果(挑战中) (已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4\) \(Completed': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4)(已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4\) \(In Challenge': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4)(挑战中',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4\) \(In Challenge\) \(Completed': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4)(挑战中) (已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4',
    'Cases boost \'Genetic ReShuffle\'.': '基于病例加成"基因重组"',
    'Infectivity makes uncoaters cheaper.': '基于传染降低脱壳者价格',
    'Cases boost replicators 1st effect base.': '基于病例加成复制的第一个加成',
    'VP boosts \'Transcription\' and makes \'Transmission\' softcap weaker.': '基于病毒点数加成"感染"且使"感染"的软上限更弱',
    'which produces': '可以产生',
    'severity  \(softcapped\)  per second.': '严重性(已达软上限)每秒',
    'severity per second.': '严重性每秒',
    'You have': '你有',
    'severity, which boosts cases, VP, and infectivity by': '严重性，加成病例、病毒点数和传染',
    'Severity boosts uncoaters 1st effect base.': '基于严重性加成脱壳者的第一个加成',
    'Uncoaters 2nd effect is boosted by bought symptom upgrades.': '基于已购买的症状升级数加成脱壳者的第二个加成',
    'Symptoms boost uncoaters 1st effect base.': '基于症状加成脱壳者的第一个加成',
    'Infectivity boost severity gain.': '基于传染加成严重性获取',
    'Severity boosts replicators 1st effect base.': '基于严重性加成复制的第一个加成',
    '\'Fever\' boosts severity effect.': '基于"发热"加成严重性效果',
    '\'Infectivity Gain\' gives free levels to \'Severity Gain\'.': '"传染获取"会提供额外的"严重性获取"等级',
    '\'Symptom Base\' gives free levels to \'Severity Gain\'.': '"症状基础"会提供额外的"严重性获取"等级',
    'Symptoms boost \'Infection\' base.': '基于症状加成"感染"',
    '\'Uncoater Base\' gives free levels to \'Infectivity Gain\'.': '"脱壳者基础"会提供额外的"传染获取"等级',
    '\'Uncoater Base\' gives free levels to \'Symptom Base\' and autobuy buyables once per second.': '"脱壳者基础"会提供额外的"症状基础"等级且每秒自动购买购买项',
    'Replicators boost severity gain.': '基于复制加成严重性获取',
    '\'Severity Gain\' base is increased by 0.0002 per level.': '"严重性获取"每级增加基础0.0002',
    '\'Coated Boost\' gives free \'Infectivity gain\'.': '"已脱壳加成"会提供额外的"传染获取"等级',
    'Cases boost symptom base.': '基于病例加成症状',
    'Deaths reduce \'Coated Boost\' scaling base.': '基于死亡降低"已脱壳加成"涨价速度',
    'Severity reduces \'Uncoater Base\' scaling base.': '基于严重性降低"脱壳者基础"涨价速度',
    'Cases reduce \'Infection Base\' scaling base.': '基于病例降低"感染基础"涨价速度',
    '\'Infection Base\' gives free \'Coated Boost\' and \'Uncoater Base\'.': '"感染基础"会提供额外的"已脱壳加成"和"脱壳者基础"等级',
    'Each \'Infection Base\' adds 0.0001 to \'Symptom Base\' base.': '每个"感染基础"会增加"症状基础"的基础0.0001',
    'Cases boost severity effect.': '基于病例加成严重性效果',
    'Infectivity boosts \'Deadly\'.': '基于传染加成"致死性"',
    'Uncoaters boost severity gain exponent.': '基于脱壳者加成严重性获取指数',
    'Replicators boost severity gain exponent.': '基于复制加成严重性获取指数',
    'Severity boosts \'Transmission\', \'Smell Loss\' buys 25x more, and unlock a row of death upgrades.': '基于严重性加成"传播"，"嗅觉丧失"购买量25×，解锁一排死亡升级',
    'Unlock buyables.': '解锁购买项',
    'Unlock 2 more buyables.': '解锁两个额外的购买项',
    'Symptoms and severity are useless. Cases gain is \^0.1. \(Completed': '症状和严重性没有效果，病例获取^0.1 (已完成',
    'Symptoms and severity are useless. Cases gain is \^0.1. \(In Challenge': '症状和严重性没有效果，病例获取^0.1 (挑战中',
    'Symptoms and severity are useless. Cases gain is \^0.1. \(In Challenge\) \(Completed': '症状和严重性没有效果，病例获取^0.1 (挑战中) (已完成',
    'Symptoms and severity are useless. Cases gain is \^0.1.': '症状和严重性没有效果，病例获取^0.1',
    'Symptom buyables are useless. Cases gain is \^0.01. \(Completed': '症状购买项没有效果，病例获取^0.01 (已完成',
    'Symptom buyables are useless. Cases gain is \^0.01. \(In Challenge': '症状购买项没有效果，病例获取^0.01 (挑战中',
    'Symptom buyables are useless. Cases gain is \^0.01. \(In Challenge\) \(Completed': '症状购买项没有效果，病例获取^0.01 (挑战中) (已完成',
    'Symptom buyables are useless. Cases gain is \^0.01.': '症状购买项没有效果，病例获取^0.01',
    'Row 3 Upgrades are useless. Cases gain is \^0.03. \(Completed': '第三排升级没有效果，病例获取^0.03 (已完成',
    'Row 3 Upgrades are useless. Cases gain is \^0.03. \(In Challenge': '第三排升级没有效果，病例获取^0.03 (挑战中',
    'Row 3 Upgrades are useless. Cases gain is \^0.03. \(In Challenge\) \(Completed': '第三排升级没有效果，病例获取^0.03 (挑战中) (已完成',
    'Row 3 Upgrades are useless. Cases gain is \^0.03.': '第三排升级没有效果，病例获取^0.03',
    '\'Asymptomatic\' and \'Unbuyable\' at once. \(Completed': '同时进行"无症状"和"无购买项" (已完成',
    '\'Asymptomatic\' and \'Unbuyable\' at once. \(In Challenge': '同时进行"无症状"和"无购买项" (挑战中',
    '\'Asymptomatic\' and \'Unbuyable\' at once. \(In Challenge\) \(Completed': '同时进行"无症状"和"无购买项" (挑战中) (已完成',
    '\'Asymptomatic\' and \'Unbuyable\' at once.': '同时进行"无症状"和"无购买项"',
    'Cases boost severity gain.': '基于病例加成严重性获取',
    'Infectivity boosts death gain.': '基于感染加成死亡获取',
    'Deaths boost \'Discoloration\'.': '基于死亡加成"变色"',
    'Severity boosts severity gain.': '基于严重性加成严重性获取',
    'which boost cases, VP, infectivity, and severity gain by': '可以加成病例、病毒点数、传染和严重性获取',
    '\(based on best\).': '(基于最高)',
    'You are gaining': '你获得',
    'deaths per second': '死亡每秒',
    'Your best deaths is ee': '你的最高死亡为ee',
    'Your best deaths is e': '你的最高死亡为e',
    'Your best deaths is': '你的最高死亡为',
    'Deaths reset all previous progress.': '死亡会重置前面所有进度',
    'Deaths boosts symptom base.': '基于死亡加成症状',
    'Cases boost death gain.': '基于病例加成死亡获取',
    'Deaths boost \'Infectivity Gain\' base.': '基于死亡加成"传染获取"',
    'Deaths boost \'Transmission\'.': '基于死亡加成"传播"',
    'Deaths boost uncoater base.': '基于死亡加成脱壳者',
    'Double death gain per death upgrade bought.': '每个死亡升级使死亡获取翻倍',
    '\'Smell Loss\' buys 2x more.': '"嗅觉丧失"购买量2×',
    'Severity boosts death gain.': '基于严重性加成死亡获取',
    'Deaths boost severity gain.': '基于死亡加成严重性获取',
    'Cases boost severity gain and \'Smell Loss\' buys 5x more.': '基于病例加成严重性获取且"嗅觉丧失"购买量5×',
    'VP boost \'Fatal\' and \'Smell Loss\' buys 2x more and 2x often.': '基于病毒点数加成"致命"且"嗅觉丧失"购买量和频率2x',
    'Bought death upgrades boost \'Fever\' and unlock more symptom upgrades.': '基于已购买死亡升级加成"发热"并解锁更多症状升级',
    'Deaths make symptom scaling start later.': '基于死亡延缓症状涨价',
    'Stop gaining recoveries and upgrades that reduce recovery effect boost severity gain.': '停止获得恢复和降低恢复效果提高严重性获取的升级',
    'Deaths boost cases gain.': '基于死亡加成病例获取',
    'Deaths boost severity gain exponent.': '基于死亡加成严重性指数',
    'Keep uncoater\/symptom milestones on reset.': '重置保留脱壳者/症状里程碑',
    'You can buy max uncoaters.': '脱壳者可以购买最大',
    'Autobuy uncoaters and unlock upgrades.': '自动购买脱壳者并解锁升级',
    'Keep uncoater challenge completions.': '保留脱壳者挑战进度',
    '\'Smell Loss\' buys 10x more and buyables cost nothing.': '"嗅觉丧失"购买量10×且购买无消耗',
    'Uncoaters reset nothing.': '脱壳者不再重置任何东西',
    'Keep previous upgrades on reset.': '重置保留前面的升级',
    'Autobuy symptoms.': '自动购买症状',
    'Unlock symptom challenges.': '解锁症状挑战',
    'Symptoms reset nothing and \'Smell Loss\' buys 2x often.': '症状不再重置任何东西且"嗅觉丧失"购买频率2×',
    'Gain 1% of death gain per second and disable prestige.': '每秒获得重置可获得的1%死亡且禁用死亡重置',
    'Buyables give free levels to the previous layer buyable.': '购买项会使前面层级的购买项获得额外等级',
    'which boost cases, VP, infectivity, severity by': '可以加成病例、病毒点数、传染和严重性',
    ', and death gain by': '，并且死亡获取提高',
    'fatality per second': '致死性每秒',
    'Your best fatality is e': '你的最高致死性为e',
    'Your best fatality is': '你的最高致死性为',
    'Keep first 5 death milestones on reset.': '重置保留前五个死亡里程碑',
    'Keep next 6 death milestones on reset.': '重置保留接下来的六个死亡里程碑',
    'Keep symptom challenges on reset.': '重置保留症状挑战进度',
    'Unlock death buyables.': '解锁死亡购买项',
    'Unlock fatality dimensions and death buyables cost nothing.': '解锁致死维度且死亡购买项无消耗',
    'Gain 1% of fatality gain per second.': '每秒获得重置可获得的1%致死性',
    'Unlock Dimension Multiplier and autobuyers buy 100x more.': '解锁维度倍增器且自动购买者购买量100x',
    'Gain 100% of fatality gain per second and disable prestige.': '每秒获得重置可获得的100%致死性并禁用重置',
    'Unlock Dimension Shifts and dimensions cost nothing.': '解锁维度转换且维度无消耗',
    'Unlock Multiplier Boosts and buy max Dimension Boosts.': '解锁倍增器加成和最大购买维度加成',
    'Unlock Casualty and buy max Multiplier Boosts.': '解锁受害者和最大购买倍增器加成',
    'Multiplier Boosts don\'t reset Dimension Boosts and unlock Auto Sacrifice.': '倍增器加成不再重置维度加成，解锁自动献祭',
    'Dimension Boosts and Sacrifice reset nothing.': '维度加成和献祭不再重置任何东西',
    'Multiplier Boosts reset nothing.': '倍增器加成不再重置任何东西',
    'Unlock Casualty Dimensions.': '解锁受害者维度',
    'Unlock Casuals.': '解锁受害',
    'Gain 1% of casualty gain per second, autobuy Casualty Multiplier, Casualty Multiplier costs nothing, and disable prestige.': '每秒获得重置可获得的1%受害者，自动购买受害者倍增器且无消耗，禁用受害者重置',
    'Autobuy Casualty Dimensions and they cost nothing.': '自动购买受害者维度且无消耗',
    'Unlock Casual Virus and Replicated Boost Autobuyer.': '解锁受害病毒和复制加成自动购买者',
    'Unlock Casual Virus buyables.': '解锁受害病毒购买项',
    'Symptoms boost severity after softcap at reduced effect.': '症状在软上限之后对严重性仍有较低加成',
    'Deaths boost fatality gain.': '基于死亡加成致命性获取',
    '\'Asymptomatic\' reward is applied after softcap at reduced effect.': '"无症状"在软上限之后仍有较低加成',
    'Cases boost fatality gain.': '基于病例加成致死性获取',
    'Fatality 1st effect is applied after softcap and is stronger based on deaths.': '基于死亡加成致死性第一项加成且在软上限之后仍有较低加成',
    'Fatality boosts severity gain exponent and unlock 3 more symptom buyables.': '基于致死性加成严重性指数并解锁三个症状购买项',
    'Severity boosts fatality gain.': '基于严重性加成致死性获取',
    'Fatality boosts death gain.': '基于致死性加成死亡获取',
    'Infectivity boosts fatality gain.': '基于传染加成致死性获取',
    'Add 1 to base fatality gain exponent and autobuy death buyables 100 per second.': '致死性基础指数+1且每秒自动购买100个死亡购买项',
    'Infectivity boosts \'Fatal\'.': '基于传染加成"致命"',
    'Cases add to the fatality exponent.': '基于病例加成致命性指数',
    'Fatality power boosts \'Infection\'.': '基于致死性力量加成"感染"',
    'Fatality boosts fatality power gain.': '基于致死性加成致死性获取',
    'Deaths boost fatality dimensions.': '基于死亡加成致死性维度',
    'Cases boost fatality dimensions.': '基于病例加成致死性维度',
    'Fatality power boosts fatality exponent.': '基于致死性力量加成致死性指数',
    'Fatality power boosts cases gain.': '基于致死性力量加成病例获取',
    'Fatality boosts cases gain.': '基于致死性加成病例获取',
    'Fatality power boosts death gain.': '基于致死性力量加成死亡获取',
    'Deaths add to the fatality exponent.': '基于死亡增加致死性指数',
    'Severity boosts fatality dimensions.': '基于严重性加成致死性维度',
    'Infectivity increases multiplier per dimension.': '基于传染增加每个维度的倍率',
    'Fatality boosts uncoaters 1st effect.': '基于致死性加成脱壳者第一项加成',
    'Uncoaters boost fatality dimensions.': '基于脱壳者加成致死性维度',
    'Replicators boost fatality dimensions.': '基于复制加成致死性维度',
    'Replicators boost fatality power effect.': '基于复制加成致死性力量效果',
    'Fatality adds to the Dimension Multiplier base.': '基于致死性增加维度倍增器基础',
    'Cases add to the Dimension Multiplier base.': '基于病例增加维度倍增器基础',
    'Reduce the Dimension and Dimension Boost cost scaling by 1.': '降低维度和维度加成膨胀速度1',
    'Fatality Dimension 8 gives 2 free \'Cases Boost\'.': '致死性维度8额外提供2个"病例加成"',
    'Multiply the Dimension Boost base by 2.': '维度加成基础乘以2',
    'Reduce the Dimension cost scaling by 1 and autobuyers buy 1,000x more and 2x faster.': '降低维度价格膨胀速度1且自动购买者购买量1000x频率2x',
    'Reduce the Dimension Boost cost scaling by 0.5.': '降低维度加成价格膨胀0.5',
    'Multiply Dimension Boost base by 5 and Multiplier Boost is 1.125x stronger.': '维度加成基础乘5，倍增器加成乘1.125',
    'fatality power, which boosts fatality gain by': '致死性力量，可以加成致死性获取',
    'VP boosts fatality dimensions.': '基于病毒点数加成致死性维度',
    'Increase the multiplier per Dimension by +0.3.': '每个维度的基础倍数+0.3',
    'Unlock Sacrifice.': '解锁献祭',
    'You start with 2 Dimension Shifts, Reduce Dimension scaling by 1, Dimension Boost scaling by 0.5.': '你可以从2维度转换开始，降低维度价格膨胀1，维度加成价格膨胀0.5',
    'Your best fatality is': '你的最高致死性为',
    'Your best fatality is e': '你的最高致死性为e',
    'Your best fatality is ee': '你的最高致死性为ee',
    'Deaths boost casualty gain.': '基于死亡加成受害者获取',
    'Total casualty boosts Fatality Dimension 1 and 8.': '基于总受害者加成致死性维度1和8',
    'Total casualty boosts Fatality Dimension 2 and 7.': '基于总受害者加成致死性维度2和7',
    'Total casualty boosts Fatality Dimension 3 and 6.': '基于总受害者加成致死性维度3和6',
    'Total casualty boosts Fatality Dimension 4 and 5.': '基于总受害者加成致死性维度4和5',
    'Multiply Dimension Boost base by 5.': '维度加成基础乘5',
    'Fatality power boosts casualty gain.': '基于致死性力量加成受害者获取',
    'Casualty boosts cases gain.': '基于受害者加成病例获取',
    'Casualty boosts Fatality Dimensions.': '基于受害者加成致死性维度',
    'Cases boost casualty gain.': '基于病例加成受害者获取',
    'Casualty boosts Multiplier Boosts.': '受害者加成倍增器加成',
    'Reduce the Dimension, and Multiplier Boost scaling by 1.': '降低维度和倍增器加成的价格膨胀1',
    'Multiplier Boosts are 1.3x stronger.': '倍增器加成效果1.3×',
    'Gain 50% of best casualty/min.': '根据最高受害者/分钟自动获得受害者',
    'Severity boosts casualty gain.': '基于严重性加成受害者获取',
    'Multiplier Boosts are 1.35x stronger.': '倍增器加成效果1.35×',
    'Casualty boosts Dimension Boost base, Reduce Dimension scaling by 1, Dimension Boost scaling by 0.5.': '基于受害者加成维度加成基础，降低维度价格膨胀1，维度加成价格膨胀0.5',
    'Casualty gives free \'Cases Boost\' and buyable autobuyers buy \^2 more.': '受害者提供额外"病例加成"且购买项自动购买者^2',
    'Casualty boosts fatality effect.': '基于受害者加成致死性效果',
    'Casualty power boosts cases gain.': '基于受害者力量加成病例获取',
    'Casualty reduces replicate interval.': '基于受害者力量降低复制间隔',
    'Divide the max interval by 20 and Distant scaling starts 20 later.': '使最大间隔分隔为20且距离膨胀延缓20',
    'Replicators reduce interval and boost Multiplier Boosts.': '基于复制降低间隔并加成倍增器加成',
    'Reduce the Dimension and Dimension Boost scaling by 0.5.': '降低维度和维度加成价格膨胀0.5',
    'Increase the Casualty Multiplier base by \+0.1.': '受害者倍增器基础+0.1',
    'Multiplier Boosts increase \'Cases Boost\' base by \+5e-7.': '倍增器加成使"病例加成"基础+5e-7',
    'Casualty reduces \'Cases Boost\' scaling.': '基于受害者降低"病例加成"价格膨胀',
    'Cases and \'Fatally\' boost each other, buyable autobuyers buy \^10 more.': '病例和"致命的"互相加成，购买项自动购买者^10',
    'Fatality boosts cases exponent.': '基于致死性加成病例指数',
    'Fatality makes Distant scaling start later.': '基于致死性延缓距离膨胀',
    'All Challenges Unlocked': '所有挑战已解锁',
    'Fatality power\/1.8e308.': '致死性力量/1.8e308',
    'Fatality power\/1.8e308. \(Completed': '致死性力量/1.8e308 (已完成',
    'Fatality power\/1.8e308. \(In Challenge': '致死性力量/1.8e308 (挑战中',
    'Fatality power\/1.8e308. \(In Challenge\) \(Completed': '致死性力量/1.8e308 (挑战中) (已完成',
    'Multiplier per Fatality Dimension is 1.': '所有致死性维度的倍数变为1',
    'Multiplier per Fatality Dimension is 1. \(Completed': '所有致死性维度的倍数变为1 (已完成',
    'Multiplier per Fatality Dimension is 1. \(In Challenge': '所有致死性维度的倍数变为1 (挑战中',
    'Multiplier per Fatality Dimension is 1. \(In Challenge\) \(Completed': '所有致死性维度的倍数变为1 (挑战中) (已完成',
    'Dimension cost scaling is 100x.': '维度价格膨胀100x',
    'Dimension cost scaling is 100x. \(Completed': '维度价格膨胀100x (已完成',
    'Dimension cost scaling is 100x. \(In Challenge': '维度价格膨胀100x (挑战中',
    'Dimension cost scaling is 100x. \(In Challenge\) \(Completed': '维度价格膨胀100x (挑战中) (已完成',
    'You can\'t buy Dimension Boosts. Multiplier Boosts cost Fatality Dimension 6 and they are 1.5x stronger.': '你不能购买维度加成，倍增器加成消耗致死性维度6且它们强度变为1.5×',
    'You can\'t buy Dimension Boosts. Multiplier Boosts cost Fatality Dimension 6 and they are 1.5x stronger. \(Completed': '你不能购买维度加成，倍增器加成消耗致死性维度6且它们强度变为1.5× (已完成',
    'You can\'t buy Dimension Boosts. Multiplier Boosts cost Fatality Dimension 6 and they are 1.5x stronger. \(In Challenge': '你不能购买维度加成，倍增器加成消耗致死性维度6且它们强度变为1.5× (挑战中',
    'You can\'t buy Dimension Boosts. Multiplier Boosts cost Fatality Dimension 6 and they are 1.5x stronger. \(In Challenge\) \(Completed': '你不能购买维度加成，倍增器加成消耗致死性维度6且它们强度变为1.5× (挑战中) (已完成',
    'All Fatality Challenges are applied at once. You can\'t gain deaths. Fatality gain is gain from 1.000e10,450 deaths': '所有致死性挑战同时进行，你无法获得死亡，致死性获取从1.000e10,450死亡开始',
    'All Fatality Challenges are applied at once. You can\'t gain deaths. Fatality gain is gain from 1.000e10,450 deaths \(Completed': '所有致死性挑战同时进行，你无法获得死亡，致死性获取从1.000e10,450死亡开始 (已完成',
    'All Fatality Challenges are applied at once. You can\'t gain deaths. Fatality gain is gain from 1.000e10,450 deaths \(In Challenge': '所有致死性挑战同时进行，你无法获得死亡，致死性获取从1.000e10,450死亡开始 (挑战中',
    'All Fatality Challenges are applied at once. You can\'t gain deaths. Fatality gain is gain from 1.000e10,450 deaths \(In Challenge\) \(Completed': '所有致死性挑战同时进行，你无法获得死亡，致死性获取从1.000e10,450死亡开始 (挑战中) (已完成',
    'Multiplier Boosts are useless.': '倍增器加成无效',
    'Multiplier Boosts are useless. \(Completed': '倍增器加成无效 (已完成',
    'Multiplier Boosts are useless. \(In Challenge': '倍增器加成无效 (挑战中',
    'Multiplier Boosts are useless. \(In Challenge\) \(Completed': '倍增器加成无效 (挑战中) (已完成',
    'Dimension scaling is 1.8e308x': '维度价格膨胀1.8e308×',
    'Dimension scaling is 1.8e308x \(Completed': '维度价格膨胀1.8e308× (已完成',
    'Dimension scaling is 1.8e308x \(In Challenge': '维度价格膨胀1.8e308× (挑战中',
    'Dimension scaling is 1.8e308x \(In Challenge\) \(Completed': '维度价格膨胀1.8e308× (挑战中) (已完成',
    'Fatality gain is \^0.1.': '致死性获取^0.1',
    'Fatality gain is \^0.1. \(Completed': '致死性获取^0.1 (已完成',
    'Fatality gain is \^0.1. \(In Challenge': '致死性获取^0.1 (挑战中',
    'Fatality gain is \^0.1. \(In Challenge\) \(Completed': '致死性获取^0.1 (挑战中) (已完成',
    'Fatality gain exp is \^0.75.': '致死性获取经验^0.75',
    'Fatality gain exp is \^0.75. \(Completed': '致死性获取经验^0.75 (已完成',
    'Fatality gain exp is \^0.75. \(In Challenge': '致死性获取经验^0.75 (挑战中',
    'Fatality gain exp is \^0.75. \(In Challenge\) \(Completed': '致死性获取经验^0.75 (挑战中) (已完成',
    'Fatality power is useless.': '致死性力量无效',
    'Fatality power is useless. \(Completed': '致死性力量无效 (已完成',
    'Fatality power is useless. \(In Challenge': '致死性力量无效 (挑战中',
    'Fatality power is useless. \(In Challenge\) \(Completed': '致死性力量无效 (挑战中) (已完成',
    'Dimension Boosts are the only thing that boosts dimensions.': '只有维度加成可以加成维度',
    'Dimension Boosts are the only thing that boosts dimensions. \(Completed': '只有维度加成可以加成维度 (已完成',
    'Dimension Boosts are the only thing that boosts dimensions. \(In Challenge': '只有维度加成可以加成维度 (挑战中',
    'Dimension Boosts are the only thing that boosts dimensions. \(In Challenge\) \(Completed': '只有维度加成可以加成维度 (挑战中) (已完成',
    'Casualty power is the only thing that boosts dimensions.': '只有受害者力量可以加成维度',
    'Casualty power is the only thing that boosts dimensions. \(Completed': '只有受害者力量可以加成维度 (已完成',
    'Casualty power is the only thing that boosts dimensions. \(In Challenge': '只有受害者力量可以加成维度 (挑战中',
    'Casualty power is the only thing that boosts dimensions. \(In Challenge\) \(Completed': '只有受害者力量可以加成维度 (挑战中) (已完成',
    'Unlock Fatality Dimension 1,2,3 Autobuyer.': '解锁致死性维度1,2,3自动购买者',
    'Unlock Fatality Dimension 4,5,6 Autobuyer.': '解锁致死性维度4,5,6自动购买者',
    'Unlock Fatality Dimension 7,8, Multiplier Autobuyer.': '解锁致死性维度7,8,倍增器自动购买者',
    'Unlock Dimension and Multiplier Boost Autobuyer.': '解锁维度和倍增器加成自动购买者',
    'Casualty boosts Casualty Dimensions.': '基于受害者加成受害者维度',
    'More powerful Sacrifice.': '更强的献祭',
    'Reduce the Dimension scaling by 1.': '降低维度价格膨胀1',
    'Fatality gain is \^1.05 and casualty power effect is \^1.5.': '致死性获取^1.05，受害者力量效果^1.5',
    'Multiplier Boosts are 1.2x stronger.': '倍增器加成增强1.2×',
    'Fatality Dimension Multiplier boosts Casualty Dimensions.': '基于致死性维度倍增器加成受害者维度',
    'Fatality boosts Dimension Boosts.': '基于致死性加成维度加成',
    'Fatality boosts casualty power effect.': '基于致死性加成受害者力量效果',
    'casualty power, which boosts Fatality Dimensions by': '受害者力量，可以加成致死性维度',
    'casuals, which boost Casualty Dimensions by': '受害，可以加成受害者维度',
    'Reset casuals for a Replicated Boost.': '重置受害以获得一个复制加成',
    'casual viruses per second, with a limit of': '受害病毒每秒，上限为',
    'Casual viruses add to Casualty Multiplier base.': '基于受害病毒增加受害者倍增器基础',
    'Casual viruses add to \'Cases Boost\' base.': '基于受害病毒增加"病例加成"基础',
    'Casual viruses boost Casualty Dimensions.': '基于受害病毒加成受害者维度',
    'Casual viruses reduce Dimension scaling.': '基于受害病毒降低维度膨胀',
    'Cases boost casual virus gain.': '基于病例加成受害病毒获取',
    'Raise cases to \^1.2 per Casual Virus upgrade.': '每个受害病毒升级使病例^1.2',
    'Casual viruses boosts itself and cases gain.': '受害病毒加成自身和病例获取',
    'Casual viruses boost fatality power effect.': '基于受害病毒加成致死性力量效果',
    'Fatality boosts casual virus gain.': '基于致死性加成受害病毒获取',
    'Add 1 to base casual virus gain exponent.': '使受害病毒获取基础指数+1',
    'Infectivity adds to casual virus exponent.': '基于传染加成受害病毒指数',
    'Severity adds to casual virus exponent.': '基于严重性增加受害病毒指数',
    'Replicators add to casual virus exponent.': '基于复制增加受害病毒指数',
    'Casual virus boosts casualty power effect.': '基于受害病毒加成受害者力量效果',
    'Casual viruses boost fatality gain.': '基于受害病毒加成致死性获取',
    'Casual viruses boost Multiplier Boosts.': '基于受害病毒加成倍增器加成',
    'Cases add to Casualty Multiplier base and unlock a buyable.': '基于病例增加受害者倍增器基础并解锁一个购买项',
    'Cases make \'Cases Boost\' softcap start later.': '基于病例延缓"病例加成"软上限',
    'Casual viruses make \'Cases Boost\' softcap start later.': '基于受害病毒延缓"病例加成"软上限',
    'Casual viruses boost cases exponent and unlock a buyable.': '基于受害病毒加成病例指数并解锁一个购买项',
    'Casualty adds to \'Virus Gain\' base.': '基于受害者增加"病毒获取"基础',
    'Remove cas. lim.,its form. is better,it boosts CV gain,RBs reset nothing.': '移除受害病毒上限，公式更好，加成受害病毒获取，不再重置任何东西',
    'Remove the interval limit, and unlock autobuy interval.': '移除间隔并解锁自动购买间隔',
    'Remove the rep mult limit,unlock auto mult, and it boosts itself.': '移除复制倍增器上限，解锁自动倍增器，且它加成自身',
    'Casual viruses slow interval scaling.': '基于受害病毒延缓间隔价格膨胀',
    'Cases reduce Dimension scaling and Distant scaling.': '基于病例降低维度和距离价格膨胀',
    'Each \'Virus Gain\' adds 0.05 to its base.': '每个"病毒获取"增加自身0.05基础',
    'Each SB adds 0.0033 to VE base and autobuy buyables once per second.': '每个"自身加成"增加"病毒指数"基础0.0033且每秒自动购买购买项',
    'infection power per second.': '感染力量每秒',
    'infection power, which boosts cases gain by \^': '感染力量，可以加成病例获取^',
    ', and  makes \'Cases Boost\' softcap start \+': '，并可以使"病例加成"的软上限延缓+',
    'later.': '',
    'immunity, which makes cases gain \(hardcapped\) at': '免疫，因此病例的硬上限为',
    'Infection power boosts \'Infection\' after softcap.': '基于感染力量在软上限之后加成"感染"',
    'IN power boost CV gain and \'More Exponenter\' buys 10x more and 2x faster.': '感染力量加成受害病毒获取且"更多指数"购买量10×频率2×',
    'Infection power divides immunity.': '基于感染力量降低免疫',
    'Cases boost infection power gain and divide immunity.': '基于病例加成感染力量获取并降低免疫',
    'Infecters add to \'Cases Boost\' base, S and D autobuyers buy max.': '基于感染者增加"病例加成"基础，症状和死亡自动购买最大',
    'Infectivity divides immunity and boosts \'Infection\' after softcap.': '基于传染降低免疫且在软上限之后加成"感染"',
    'Infectivity boosts IN power gain and dimension autobuyers buy 1,000,000x more.': '基于传染加成感染力量获取且维度自动购买量1,000,000×',
    'Infection power adds to infecter base.': '基于感染力量增加感染者基础',
    'Casuals boost IN power gain and \'More Exponenter\' buys 100x more and 2x faster.': '基于受害加成感染力量获取且"更多指数"购买量100×频率2×',
    'IN power boosts \'Unlimited Casuals\' and \'Unlimited Multiplier\'.': '基于感染力量加成"非免疫受害"和"非免疫倍增器"',
    'Casuals divide immunity.': '受害降低免疫',
    'Casualty divides immunity and adds to infecter base.': '受害者降低免疫并增加感染者基础',
    'Casuals boost infection power 1st effect.': '基于受害加成感染力量第一项加成',
    'Multiplier Boosts boost infection power gain.': '基于倍增器加成加成感染力量获取',
    'Multiplier Boosts divide immunity.': '基于倍增器加成降低免疫',
    'Infection power divides \'Self Booster\' scaling base and its softcap starts 400 later.': '基于感染力量降低"自身加成"价格膨胀且它的软上限延缓400',
    'Infection power makes Social Distant scaling start later and Dimension scaling is \^0.05.': '基于感染力量延缓远距离价格膨胀且维度价格膨胀^0.05',
    'Fatality power boosts infection power gain.': '基于致死性力量加成感染力量获取',
    'Fatality power adds to \'Power Base\' base.': '基于致死性力量增加"力量基础"基础',
    '\'Infected Infectivity\' boosts itself.': '"传染感染"加成自身',
    'Cases boost its exponent.': '基于病例加成它的指数',
    'Infectious diseases give infected infections.': '感染性疾病会传染感染',
    'Add 0.005 to \'Disease Boost\' base.': '"疾病加成"基础增加0.005',
    'Cases produce infected infections and unlock Quarantine.': '病例产生传染感染并解锁防疫',
    'IP makes Distant Cases Boost scaling start later.': '基于感染力量延缓距离病例加成价格膨胀',
    'IP adds to \'UC Gain\' and \'Cases Base\' base.': '基于感染力量增加"脱壳获取"和"病例基础"基础',
    'Fatality adds to \'Quarantine Boost\' base': '基于致死性加成"防疫加成"基础',
    'Fatality power boosts fatality gain and unlock a buyable \(no auto\).': '基于致死性力量加成致死性获取并解锁一个购买项(无自动)',
    'UC boosts ID effect exponent': '基于反防疫病例加成感染疾病效果指数',
    'IP boosts cases exponent and unlock RNA.': '基于感染力量加成病例指数并解锁RNA',
    'Unlock Buyables and Casual Virus buyables cost nothing.': '解锁购买项且受害者病毒购买项无消耗',
    'Unlock Infected Infections.': '解锁传染感染',
    'Unlock Infectious Diseases and autobuy buyables.': '解锁感染性疾病并自动购买购买项',
    'Unlock Infection Challenges, buy max infecters, and buyables cost nothing.': '解锁感染挑战，最大购买感染者且购买项无消耗',
    'Autobuy Quarantine buyables.': '自动购买防疫购买项',
    'Autobuy Infecters and they reset nothing.': '自动购买感染者并且它不再重置任何东西',
    'Autobuy RNA buyables and Atom RNAs and they cost nothing.': '自动购买RNA购买项和原子RNA且它们无消耗',
    'Autobuy Disease buyables.': '自动购买疾病购买项',
    'Autobuy mRNA buyables and they cost nothing.': '自动购买mRNA购买项且无消耗',
    'Autobuy \'MMNA Virus\', shift buys 10x more, and it costs nothing.': '自动购买"MMNA病毒"，按shift购买10×且无消耗',
    'Autobuy MMNA buyables.': '自动购买MMNA购买项',
    'Autobuy \'Max Buyable\'.': '自动购买"最大购买项"',
    'Buyables give free levels to left buyables.': '购买项会给左边的购买项额外等级',
    'Each buyable gives 1 infected infection.': '每个购买项提供1传染感染',
    'Each Row 2 buyable gives 10 infected infections.': '每个第二排的购买项提供10传染感染',
    'Add 1 to \'Power Gain\' base.': '"力量获取"的基础增加1',
    'Fatality divides immunity.': '基于致死性降低免疫',
    'Fatality makes Social Distant scaling weaker.': '基于致死性弱化远距离价格膨胀',
    'IN power boosts \'Disease Power\'.': '基于感染力量加成"疾病力量"',
    'IN power boosts \'Infected Cases\'.': '基于感染力量加成"传染病例"',
    'Infection power adds to \'Power Gain\' base.': '基于感染力量增加"力量获取"基础',
    'Infectious diseases add to \'Power Gain\' base.': '基于感染性疾病增加"力量获取"基础',
    'Add 0.01 to \'Immunity Divider\' base.': '"免疫降低"的基础增加0.01',
    'Add 0.05 to \'Infecter Base\' base.': '"感染者基础"的基础增加0.05',
    'Casual viruses add to \'Power Gain\' base.': '基于受害病毒增加"力量获取"基础',
    'Casual viruses boost \'Infected Casuals\'.': '基于受害病毒加成"传染受害"',
    'Casual viruses boost infecter base.': '基于受害病毒加成感染者基础',
    'Divide immunity by 1.25, and \'Self Booster\' softcap starts 1,000 later.': '降低免疫1.25，"自身加成"软上限延缓1,000',
    'Infection power makes Social Distant scaling weaker.': '基于感染力量弱化远距离价格膨胀',
    'Infectious diseases boost infecter base.': '基于感染性疾病加成感染者基础',
    'Total infected infections boost \'Power Gain\' base.': '基于总传染感染加成"力量获取"基础',
    '\'Virus Exponent\' softcap is weaker.': '弱化"病毒指数"的软上限',
    '\'More Infections\' is applied after softcap at reduced rate.': '"更多感染"在软上限之后仍有较低加成',
    '\'Disease\' boosts \'Infection\' after softcap.': '基于"疾病"在软上限之后加成"感染"',
    'Add 0.025 to \'Disease Gain\' base.': '"疾病获取"的基础增加0.025',
    'Cases boost base infectious disease gain.': '基于病例加成基础感染性疾病获取',
    'Cases boost IP and ID effect exponent and unlock a row of IP upgrades.': '病例加成感染力量和感染疾病效果指数并酒叟一排感染力量升级',
    'Cases slow interval scaling.': '基于病例延缓传染膨胀',
    'Casual viruses boost infection power gain.': '基于受害病毒加成感染力量获取',
    'Fatality boosts infectious disease effect and dimension autobuyers buy max.': '基于致死性加成感染性疾病效果且维度自动购买最大',
    'Fatality boosts infectious disease gain.': '基于致死性加成感染性疾病获取',
    'Fatality power softcap is weaker.': '弱化致死性力量软上限',
    'Immunity boosts cases exponent.': '基于免疫加成病例指数',
    'Immunity boosts infection power gain': '基于免疫加成感染力量获取',
    'Immunity boosts infectious disease gain.': '基于免疫加成感染性疾病获取',
    'Infection 21 effect is \^5 and \'More Exponenter\' buys 1000x more and 2x faster.': '感染21效果^5且"更多指数"购买量1000×频率2×',
    'Infection power adds to \'Disease Gain\' base.': '基于感染力量增加"疾病获取"基础',
    'Infection power boosts infectious disease gain.': '基于感染力量加成感染性疾病获取',
    'Infectious diseases add to \'Immunity Divider\' base.': '基于感染性疾病增加"免疫降低"基础',
    'Infectious diseases boost \'Release\' and unlock a row of buyables.': '基于感染性疾病加成"释放"并解锁一排购买项',
    'Infectious diseases boost cases exponent.': '基于感染性疾病加成病例指数',
    'Infectious diseases boost casual virus gain.': '基于感染性疾病加成受害病毒获取',
    'Infectious diseases boost fatality power effect.': '基于感染性疾病加成致死性力量效果',
    'Infectious diseases boost infection power 1st effect.': '基于感染性疾病加成感染力量第一个效果',
    'Infectious diseases boost infection power gain.': '基于感染性疾病加成感染力量获取',
    'Infectious diseases divide immnunity and unlock a disease buyable.': '基于感染性疾病降低免疫并解锁一个疾病购买项',
    'infectious diseases, which boost Dimension Boosts by': '感染性疾病，可以加成维度加成',
    'Unspent infected infections boost infection power gain.': '基于未使用的传染感染加成感染力量获取',
    'Unspent infected infections boost infectious disease gain.': '基于未使用的传染感染加成感染性疾病获取',
    'Upgrades based on unspent infected infections are based on total.': '基于未使用的传染感染的升级现在基于总数',
    'You can pick all paths in the 3 way split.': '你可以选择所有三路传染感染升级',
    'You can pick another path in the 3 way split.': '你可以额外选择一路传染感染升级',
    '\'Cases Boost\' is useless.': '"病例加成"没有效果',
    '\'Cases Boost\' is useless. \(Completed': '"病例加成"没有效果 (已完成',
    '\'Cases Boost\' is useless. \(In Challenge': '"病例加成"没有效果 (挑战中',
    '\'Cases Boost\' is useless. \(In Challenge\) \(Completed': '"病例加成"没有效果 (挑战中) (已完成',
    'Cases gain is log10\(gain\). \(In Challenge': '病例获取变为log10(获取量) (挑战中',
    'Cases gain is log10\(gain\). \(In Challenge\) \(Completed': '病例获取变为log10(获取量) (挑战中) (已完成',
    'Cases gain is log10\(gain\).': '病例获取变为log10(获取量)',
    'Cases gain is log10\(gain\). \(Completed': '病例获取变为log10(获取量) (已完成',
    'Infectious Diseases add to \'Cases Boost\' base.': '基于感染性疾病增加"病例加成"基础',
    'Cases divide immunity.': '基于病例降低免疫',
    'infected infections per second.': '传染感染每秒',
    'Unquarantined Infections, which produce': '反防疫感染，可以生产',
    'Unquarantined Cases per second': '反防疫病例每秒',
    'Unquarantined Cases': '反防疫病例',
    'Infectious diseases boosts UC gain and \'More Exponenter\' buys \^10 more.': '基于感染性疾病加成反防疫病例获取且"更多指数"购买量^10',
    'Add 0.003 to \'Disease Boost\' base.': '"疾病加成"基础+0.003',
    'Cases add to \'UC Gain\' base.': '基于病例增加"反防疫病例获取"基础',
    'Cases boost IP 2nd effect.': '基于病例加成感染力量第二个加成',
    'Cases boost UC gain.': '基于病例加成反防疫病例获取',
    'Cases reduce \'Cases Base\' cost scaling.': '基于病例降低"病例基础"价格膨胀',
    'Cases reduce \'Disease Boost\' cost scaling.': '基于病例降低"疾病基础"价格膨胀',
    'Each \'UC Boost\' adds 0.005 to \'UI Gain\' base.': '每个"反防疫病例加成"增加"反防疫感染获取"基础0.005',
    'Fatality adds to \'Disease Gain\' base.': '基于致死性增加"疾病获取"基础',
    'Fatality boosts \'Quarantine Infecter\'.': '基于致死性加成"防疫感染者"',
    'Fatality boosts IP 2nd effect.': '基于致死性加成感染力量第二个加成',
    'Fatality boosts UI gain.': '基于致死性加成反防疫感染获取',
    'Infected infections add to \'Cases Boost\' base.': '基于传染感染增加"病例加成"基础',
    'Infected infections add to UI gain exponent.': '基于传染感染增加反防疫感染指数',
    'Infected infections boost \'Self Infection\'.': '基于传染感染加成"自身感染"',
    'Infected infections boost IN power 2nd effect.': '基于传染感染加成感染力量第二个加成',
    'Infected infections boost UC gain.': '基于传染感染加成反防疫病例获取',
    'Infecters add to \'Cases Base\' and \'UC Boost\' base.': '感染者增加"病例基础"和"反防疫病例加成"基础',
    'Infecters add to UI gain exponent.': '基于感染者增加反防疫感染指数',
    'Infection power boosts UC gain.': '基于感染力量加成反防疫病例获取',
    'Infectious diseases add to \'UC Gain\' base.': '基于感染性疾病增加"反防疫病例获取"基础',
    'Infectious diseases boost Quarantine exponent.': '基于感染性疾病加成防疫指数',
    'IP boosts Quarantine exponent.': '基于感染力量加成防疫指数',
    'MBs boost UC gain, IP 2nd eff, remove Dim sc., unlock a row of IP upgs.': '倍增器加成加成反防疫病例获取，感染力量第二个加成，移除维度膨胀，解锁一排感染力量升级',
    'Deaths reduce recovery effect.': '基于死亡降低恢复效果',
    'Cases reduce recovery effect and \'Smell Loss\' buys 5x more.': '基于病例降低恢复效果且"嗅觉丧失"购买量5×',
    'Severity reduces the recovery effect.': '基于严重性降低恢复效果',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    
    //标题
    'Start': '开始',
    'Infection': '感染',
    'Transmission': '传播',
    'Self Boost': '自身加成',
    'Contaminate': '污染',
    'More Infections': '更多感染',
    'Disease': '疾病',
    'BOOSTER': '加成者',
    'Food Contamination': '污染食物',
    'VP Boost': '病毒点数加成',
    'Air Transmission': '空气传播',
    'Resistance': '抗性',
    'Susceptible': '易感',
    'Drug Resistance': '药物抗性',
    'Environmental Hardening': '环境强化',
    'SUSceptible': '极易感',
    'Genetic Hardening': '基因强化',
    'Genetic ReShuffle': '基因重组',
    'Replication': '复制',
    'DNA': 'DNA',
    'Attachment': '拥护',
    'Entry': '参与',
    'Uncoating': '脱壳',
    'Transcription': '转录',
    'Synthesis': '合成',
    'Virion': '病毒体',
    'Release': '释放',
    'Main': '主界面',
    'Milestones': '里程碑',
    'Challenges': '挑战',
    'Uncoated Infection': '脱壳感染',
    'Water Transmission': '水源传播',
    'Synergy': '协同',
    'Genome Replication': '基因组复制',
    'Bird Transmission': '鸟类传播',
    'Viral Proteins': '病毒蛋白',
    'Viral Enzymes': '病毒酶',
    'Endocytosis': '内吞作用',
    'Coated': '已脱壳',
    'Disinfectant': '无法传染',
    'Unreplicated': '无法复制',
    'Masks': '口罩',
    'Cough': '咳嗽',
    'Fever': '发热',
    'Tiredness': '疲劳',
    'Pain': '痛苦',
    'Sore Throat': '喉咙痛',
    'Chills': '畏寒',
    'Headache': '头痛',
    'Buyables': '购买项',
    'Diarrhea': '腹泻',
    'Conjunctivitis': '结膜炎',
    'Taste Loss': '味觉丧失',
    'Smell Loss': '嗅觉丧失',
    'Skin Rash': '皮疹',
    'Discoloration': '变色',
    'Shortness of Breath': '气短',
    'Chest Pain': '胸痛',
    'Speech Loss': '失语',
    'Movement Loss': '行动丧失',
    'Pneumonia': '肺炎',
    'Fatigue': '厌倦',
    'Congestion': '淤血',
    'Muscle Aches': '肌肉酸痛',
    'Nausea': '恶心',
    'Asthma': '哮喘',
    'Cancer': '癌症',
    'Heart Failure': '心力衰竭',
    'Severity Gain': '严重性获取',
    'Infectivity Gain': '传染获取',
    '\'Coated\' Boost': '"已脱壳"加成',
    'Symptom Base': '症状基础',
    'Uncoater Base': '脱壳者基础',
    '\'Infection\' Base': '"感染"基础',
    'Severity Boost': '严重性加成',
    'Symptom Boost': '症状加成',
    'Severity Exponent': '严重性指数',
    'Asymptomatic': '无症状',
    'Unbuyable': '无购买项',
    'Row 3 Downgrade': '第三排不升级',
    'Symptomless Symptoms': '没有症状的症状',
    'Upgrades': '升级',
    'Deadly': '死亡',
    'Fatal': '致命',
    'Lethal': '致死',
    'Blood Transmission': '血液传播',
    'Dangerous': '危险性',
    'Mortal': '必死',
    'Kill': '杀死',
    'Dying': '濒死',
    'Pass Away': '去世',
    'Perish': '消亡',
    'Expire': '逝世',
    'Decease': '亡故',
    'Demise': '终焉',
    'Murder': '谋杀',
    'Slain': '杀害',
    'Slaughter': '屠杀',
    'Death Gain': '死亡获取',
    'Distant Cases Boost': '远方病例加成',
    'Dimensions': '维度',
    'Casualty': '受害者',
    'Multiplier': '倍增器',
    'Autobuyers': '自动购买者',
    'Casualty Dimensions': '受害者维度',
    'Casuals': '受害',
    'Casual Virus': '受害病毒',
    'Lethality': '致命性',
    'Deadliness': '致命',
    'Mortality': '死亡率',
    'Fatally': '致命的',
    'Fatalness': '危险性',
    'Severely': '严重的',
    'Severer': '十分严重的',
    'Deadlier': '更致命的',
    'Infectious': '感染性',
    'More Fatal': '更多致命',
    'Fataler': '更致命',
    'Fatalest': '最致命',
    'Fatal Infection': '致命感染',
    'Powerful Fatalities': '更强的致死性',
    'Death Dimension': '死亡维度',
    'Case Dimension': '病例维度',
    'Powerful Power': '强大的力量',
    'Powerful Cases': '强大的病例',
    'Fatal Fatalities': '致死性致死',
    'Deadly Power': '死亡力量',
    'Fatal Deaths': '死亡致死',
    'Severity Dimension': '严重性维度',
    'Infected Dimension': '感染维度',
    'Uncoated Fatalities': '致死性脱壳',
    'Uncoated Dimension': '脱壳维度',
    'Replicated Dimension': '复制维度',
    'Replicated Power': '复制力量',
    'Multiplied Fatalities': '致死性倍增',
    'Multiplied Cases': '病例倍增',
    'Scaling Reduction': '降低膨胀',
    '8 Dimension Cases': '病例维度8',
    'Boosted Boosts': '增强加成',
    'BULK': '大量',
    'Boost Scaling': '加成膨胀',
    'Boost Boosters': '加成增强者',
    'Sacrifice': '献祭',
    'Virus Dimension': '病毒维度',
    'Stronger Dimensions': '更强的维度',
    'Sacrificed Fatality': '致死性献祭',
    'Scaled': '膨胀',
    'Casualty Upgrades': '受害者升级',
    'Deadly Casualties': '致命的受害者',
    'Dimension': '维度',
    'Powerful Casualties': '强大的受害者',
    'Casual Casualties': '受害的受害者',
    'Casualty Boost': '受害者加成',
    'Casual Multipliers': '受害倍增器',
    'Scaled Dimension': '膨胀维度',
    'Stronger Multipliers': '更强的倍增器',
    'Casualty Auto Gain': '自动获得受害者',
    'Severe Casualties': '严重的受害者',
    'Casual Scaling': '受害膨胀',
    'Stronger Casualties': '更强的受害者',
    'Casual Boosts': '受害者加成',
    'Case-ual Boosts': '受害病例加成',
    'Fatal Casualties': '致命受害者',
    'Case PoWeR': '病力量',
    'Casual Replication': '受害复制',
    'Distance': '距离',
    'Replicated Replication': '复制复制',
    'Replicated Scaling': '复制膨胀',
    'Casual Casual': '受害受害',
    'Cases MultiBoost': '病例倍增加成',
    'Case Scaling': '病例膨胀',
    'Fatal Synergy': '致死协同',
    'Fatal Cases': '致死病例',
    'Distant Fatalities': '致死性距离',
    'Buy Max': '购买最大',
    'Distant Casualty Multiplier': '受害者距离倍增器',
    'Fatality Challenge': '致死性挑战',
    'Casualty Challenge': '受害者挑战',
    'Fatality Dimension Multiplier Autobuyer': '致死性维度倍增器自动购买者',
    'Fatality Dimension Boost Autobuyer': '致死性维度加成自动购买者',
    'Fatality Multiplier Boost Autobuyer': '致死性倍增器加成自动购买者',
    'Automatic Sacrifice': '自动献祭',
    'All Dimensions Unlocked': '所有维度已解锁',
    'Casualty Dimension': '受害者维度',
    'Casual Replicate Multiplier': '受害复制倍增器',
    'Casual Replicate Interval': '受害复制间隔',
    'Social Distant Casual Replicated Boosts': '远距离受害复制加成',
    'MultiVirus': '复杂病毒',
    'Boosted Virus': '病毒增强',
    'Casual Vimension': '受害病度',
    'Scaled Virus': '膨胀病毒',
    'Case-ual Virus': '例害病毒',
    'Case-ual Upgrades': '例害升级',
    'Self Casual Boost': '自身受害加成',
    'Powerful Viruses': '强大的病毒',
    'Fatal Virus': '致死病毒',
    'Virus Virus': '病毒病毒',
    'Infected Casual': '传染受害',
    'Severe Casual': '严重受害',
    'Replicated Casual': '复制受害',
    'Powerful Casuals': '强大的受害',
    'Fatal Casual': '致死受害',
    'Casual MultiVoost': '受害倍加成',
    'Case-ual Multipliers': '例害倍增器',
    'Infected Softcaps': '传染软上限',
    'Casual Softcaps': '受害软上限',
    'Exponent Exponent': '指数指数',
    'Casualer Virus': '受害者病毒',
    'Unlimited Casuals': '非免疫受害',
    'Unlimited Interval': '非免疫间隔',
    'Unlimited Multiplier': '非免疫倍增器',
    'Faster Replication': '更快的复制',
    'Slow Scaling': '缓慢膨胀',
    'Casualest Virus': '最受害病毒',
    'More Exponenter': '更多指数',
    'Virus Gain': '病毒获取',
    'Virus Exponent': '病毒指数',
    'Self Booster': '自身加成',
    'Infections': '感染',
    'Diseases': '疾病',
    'Quarantine': '防疫',
    'Infected': '传染',
    'Infected Virus': '传染病毒',
    'Infected Immunity': '传染免疫',
    'Infected Cases': '传染病例',
    'Infected Boost': '传染加成',
    'Infect Infect': '传染传染',
    'Infected Infectivity': '传染感染',
    'Infected Infecters': '传染感染者',
    'Infected Casuals': '传染受害',
    'Casualer Infection': '受害者感染',
    'Casual Immunity': '受害免疫',
    'Infected Casualty': '传染受害者',
    'Powerful Infection': '强大的感染',
    'Multiplied Infection': '倍增感染',
    'MultiDivide Immunity': '倍减免疫',
    'Self Voost': '自身超加成',
    'Distant Distancing': '拉开距离',
    'Fataler Infection': '致死性感染',
    'Fatal Base': '致死基础',
    'Self Infection': '自身感染',
    'Self Exponent': '自身指数',
    'Infected Diseaser': '传染疾病',
    'Diseaser Boost': '疾病加成',
    'PROduction': '专业生产',
    'Distant Infection': '距离感染',
    'Powerful Bases': '更强的基础',
    'Fatally Quarantined': '致死性防疫',
    'Fataler Fatality': '致死性致死者',
    'Diseaser Quarantine': '疾病防疫',
    'Powerful Infections': '强大的感染',
    'Immunity Base': '免疫基础',
    'Power Gain': '力量获取',
    'Infecter Base': '感染者基础',
    'Immunity Divider': '免疫降低',
    'Power Base': '力量基础',
    'Infecter Base\^': '感染者基础^',
    'Max Buyable': '最大购买项',
    'Case Base': '病例基础',
    'Casual Disease': '病例疾病',
    'Disease Boost': '疾病加成',
    'Disease Gain': '疾病获取',
    'Disease Immunity': '疾病免疫',
    'Disease Power': '疾病力量',
    'Diseased': '重疾',
    'Diseaser': '疾病制造者',
    'Disfectease': '传染性疾病',
    'Divided Disease': '降低疾病',
    'Fatal Disease': '致命疾病',
    'Fataler Disease': '更致命疾病',
    'Fatalest Disease': '最致命疾病',
    'Immune Cases': '免疫病例',
    'Immunity Power': '免疫力量',
    'Infected Disease': '传染疾病',
    'Infected Infectious': '传染感染性',
    'Infected Power': '传染力量',
    'Infected Scales': '传染膨胀',
    'Infectious Cases': '感染性病例',
    'Infectious Infecters': '感染性感染者',
    'Infectious Power': '感染性力量',
    'Infrection': '再感染',
    'Ininfection': '正在感染',
    'Offline Time': '离线时间',
    'Play Again': '重玩',
    'Powered Powers': '强大的力量',
    'Powerful Disease': '强大的疾病',
    'Softer Power': '柔软的力量',
    'Released Diseases': '释放疾病',
    'Totally Infected': '总计传染',
    'Virus Power': '病毒力量',
    'Bulck': '别克',
    'Boostless': '无加成',
    'Logarithm': '对数',
    'Unquarantined Power': '反防疫力量',
    'UC Boost': '反防疫病例加成',
    'UC Gain': '反防疫病例获取',
    'UI Boost': '反防疫感染加成',
    'UI Gain': '反防疫感染获取',
    'UnQuarantine': '反防疫',
    'Unquarantined Base': '反防疫基础',
    'Unquarantined Boost': '反防疫加成',
    'Unquarantined Disease': '反防疫疾病',
    'Unquarantined Immunity': '反防疫免疫',
    'Unquarantined Infrection': '反防疫再感染',
    'Unquarantined Infection': '反防疫感染',
    'Quarantine Boost': '防疫加成',
    'Cases Base': '病例基础',
    'Infectious Quarantine': '感染性防疫',
    'Infected Quarantine': '传染防疫',
    'Quarantine Power': '防疫力量',
    'Cased Quarantine': '病例防疫',
    'Quarantine Infecter': '防疫感染者',
    'Self Unquarantine': '自身反防疫',
    'Infected Self': '传染自身',
    'InBoofecsted Power': '传染加成力量',
    'Diseased Quarantine': '疾病防疫',
    'Diseasest Boost': '最疾病加成',
    'Infected Expower': '传染指数力量',
    'DiseasedTine': '防疾病疫',
    '\'UN\'Quarantine': '"反"防疫',
    'Powered Quarantine': '强大的防疫',
    'Powerful Unquarantine': '更强大的反防疫',
    'Fatal Unquarantine': '致死反防疫',
    'Fatal Softcap': '致死软上限',
    'Fatal Infecter': '致死感染者',
    'Fataler Unquarantine': '致死者反防疫',
    'Infecter Booster': '感染者加成',
    'QuarUntined Cases': '反防疫病例',
    'Cased Cases': '病例病例',
    'Softer Softpower': '更软的软上限',
    'Scaled Cases': '病例膨胀',
    'Scaled Disease': '疾病膨胀',
    'Fatal Scaling': '致死膨胀',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    'Current endgame: e3.689e12 mRNA \(v0.': '当前游戏终点：e3.689e12mRNA (v0.',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(\d+) uncoaters$/, '$1 脱壳者'],
    [/^e(\d+),(\d+)e(\d+),$/, 'e$1,$2e$3,'],
    [/^e(\d+).(\d+)e(\d+),$/, 'e$1.$2e$3,'],
    [/^e(\d+).(\d+)e$/, 'e$1.$2e'],
    [/^(\d+).(\d+)e(\d+),(\d+),$/, '$1.$2e$3,$4,'],
    [/^(\d+).(\d+)e(\d+),$/, '$1.$2e$3,'],
    [/^e-(\d+).(\d+)e(\d+),$/, 'e-$1.$2e$3,'],
    [/^(\d+) symptoms$/, '$1 症状'],
    [/^(\d+) total death$/, '$1 总死亡'],
    [/^Completed:(\d+)\/$/, '已完成:$1/'],
    [/^Fatality Dimension (\d+) Autobuyer$/, '致死性维度$1自动购买者'],
    [/^Cost: (.+) virus points\n			$/, '消耗：$1病毒点数\n			'],
    [/^Cost: (.+) replicators\n			$/, '消耗：$1复制\n			'],
    [/^Cost: (.+) infectivity\n			$/, '消耗：$1传染\n			'],
    [/^Cost: (.+) uncoaters\n			$/, '消耗：$1脱壳者\n			'],
    [/^Cost: (.+) severity\n			$/, '消耗：$1严重性\n			'],
    [/^Cost: (.+) symptoms\n			$/, '消耗：$1症状\n			'],
    [/^Cost: (.+) infection power\n			$/, '消耗：$1感染力量\n			'],
    [/^Cost: (.+) fatality\n			$/, '消耗：$1致死性\n			'],
    [/^Cost: (.+) deaths\n			$/, '消耗：$1死亡\n			'],
    [/^Cost: (.+) casualty\n			$/, '消耗：$1受害者\n			'],
    [/^Cost: (.+) infected infections\n			$/, '消耗：$1传染感染\n			'],
    [/^Cost: (.+) casual viruses\n			$/, '消耗：$1受害病毒\n			'],
    [/^Cost: (.+) Unquarantined Cases\n			$/, '消耗：$1反防疫病例\n			'],
    [/^Cost: (.+) infectious diseases\n			$/, '消耗：$1感染性疾病\n			'],
    [/^\^(.+) \(softcapped$/, '^$1 (已达软上限'],
    [/^(.+)x \(softcapped$/, '$1x (已达软上限'],
    [/^Last save was (.+)s ago.$/, '上次保存在$1秒之前'],
    [/^Multiply severity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '严重性获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply severity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '严重性获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Multiply the uncoater base by (.+) \(based on cases\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '脱壳者基础加成$1(基于病例)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply the uncoater base by (.+) \(based on cases\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '脱壳者基础加成$1(基于病例)\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Increase \'Symptom Base\' base by (.+) \(based on fatality and severity\)\n                Cost: (.+) severity\n                Effect: \+(.+)\n                Amount: (.+)$/, '增加"症状基础"$1(基于致死性和严重性)\n                消耗：$2严重性\n                效果：+$3\n                数量:$4'],
    [/^Increase \'Symptom Base\' base by (.+) \(based on fatality and severity\)\n                Cost: (.+) severity\n                Effect: \+(.+)\n                Amount$/, '增加"症状基础"$1(基于致死性和严重性)\n                消耗：$2严重性\n                效果：+$3\n                数量'],
    [/^Multiply \'Severity Gain\' base by (.+) \(based on deaths\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '"严重性获取"基础加成$1(基于死亡)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply \'Severity Gain\' base by (.+) \(based on deaths\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '"严重性获取"基础加成$1(基于死亡)\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Multiply \'Infection\' base by (.+). \(based on VP\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '"感染"基础加成$1(基于病毒点数)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply \'Infection\' base by (.+). \(based on VP\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '"感染"基础加成$1(基于病毒点数)\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Multiply the symptom base by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '症状基础加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply the symptom base by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '症状基础加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Multiply Infectivity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount$/, '传染获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量'],
    [/^Multiply Infectivity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '传染获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Raise \'Coated\' reward to \^\(1\+(.+)x\) \(based on infectivity\)\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount$/, '增加"已脱壳"奖励^(1+$1) (基于传染)\n                消耗：$2严重性\n                效果：^$3\n                数量'],
    [/^Raise \'Coated\' reward to \^\(1\+(.+)x\) \(based on infectivity\)\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount: (.+)$/, '增加"已脱壳"奖励^(1+$1) (基于传染)\n                消耗：$2严重性\n                效果：^$3\n                数量:$4'],
    [/^Increase severity gain exponent by (.+) \(based on cases and infectivity\) and gives free levels to all previous buyables\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount: (.+)$/, '增加严重性获取指数$1(基于病例和传染)且增加前面所有购买项的等级\n                消耗：$2严重性\n                效果：^$3\n                数量:$4'],
    [/^Increase severity gain exponent by (.+) \(based on cases and infectivity\) and gives free levels to all previous buyables\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount$/, '增加严重性获取指数$1(基于病例和传染)且增加前面所有购买项的等级\n                消耗：$2严重性\n                效果：^$3\n                数量'],
    [/^Multiply severity gain by (.+) after softcap \(based on deaths\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount: (.+)$/, '严重性获取加成$1在软上限之后(基于死亡)\n                消耗：$2死亡\n                效果：$3×\n                数量:$4'],
    [/^Multiply severity gain by (.+) after softcap \(based on deaths\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount$/, '严重性获取加成$1在软上限之后(基于死亡)\n                消耗：$2死亡\n                效果：$3×\n                数量'],
    [/^Multiply death gain by (.+) \(based on fatality\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount: (.+)$/, '死亡获取加成$1(基于致死性)\n                消耗：$2死亡\n                效果：$3×\n                数量:$4'],
    [/^Multiply death gain by (.+) \(based on fatality\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount$/, '死亡获取加成$1(基于致死性)\n                消耗：$2死亡\n                效果：$3×\n                数量'],
    [/^Raise cases gain to (.+) \(based on cases\).\n                Cost: (.+) deaths\n                Effect: \^(.+) \(softcapped\)\n                Amount: (.+)$/, '病例获取指数增加$1(基于病例)\n                消耗：$2死亡\n                效果：^$3(已达软上限)\n                数量:$4'],
    [/^Raise cases gain to (.+) \(based on cases\).\n                Cost: (.+) deaths\n                Effect: \^(.+)\n                Amount: (.+)$/, '病例获取指数增加$1(基于病例)\n                消耗：$2死亡\n                效果：^$3\n                数量:$4'],
    [/^Raise cases gain to (.+) \(based on cases\).\n                Cost: (.+) deaths\n                Effect: \^(.+)\n                Amount$/, '病例获取指数增加$1(基于病例)\n                消耗：$2死亡\n                效果：^$3\n                数量'],
    [/^Produces fatality power.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount(.+)$/, '生产致死性力量\n                消耗：$1 致死性\n                倍数：$2×\n                数量$3'],
    [/^Produces fatality power.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount$/, '生产致死性力量\n                消耗：$1 致死性\n                倍数：$2×\n                数量'],
    [/^Produces Fatality Dimension (\d+).\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount(.+)$/, '生产致死性维度$1\n                消耗：$2 致死性\n                倍数：$3×\n                数量$4'],
    [/^Produces Fatality Dimension (\d+).\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount$/, '生产致死性维度$1\n                消耗：$2 致死性\n                倍数：$3×\n                数量'],
    [/^Multiply fatality dimensions by (.+)\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount(.+)$/, '致死性维度乘以$1\n                消耗：$2 致死性\n                倍数：$3×\n                数量$4'],
    [/^Multiply fatality dimensions by (.+)\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount$/, '致死性维度乘以$1\n                消耗：$2 致死性\n                倍数：$3×\n                数量'],
    [/^Multiply fatality dimensions by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount(.+)$/, '致死性维度乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量$4'],
    [/^Multiply fatality dimensions by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount$/, '致死性维度乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量'],
    [/^Reset Dimension Boosts, and multiply Fatality Dimension Multiplier base by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount(.+)$/, '重置维度加成并使致死性维度倍增器基础乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量$4'],
    [/^Reset Dimension Boosts, and multiply Fatality Dimension Multiplier base by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount$/, '重置维度加成并使致死性维度倍增器基础乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量'],
    [/^Multiply fatality dimensions by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount$/, '致死性维度乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量'],
    [/^Reset Dimension Boosts, and multiply Fatality Dimension Multiplier base by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount$/, '重置维度加成并使致死性维度倍增器基础乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量'],
    [/^Multiply Casualty gain by (.+)\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount(.+)$/, '受害者获取乘以$1\n                消耗：$2 受害者\n                倍数：$3×\n                数量$4'],
    [/^Multiply Casualty gain by (.+)\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount$/, '受害者获取乘以$1\n                消耗：$2 受害者\n                倍数：$3×\n                数量'],
    [/^Autobuys Fatality Dimension (\d+).\(MAXED\)\n                Cost: (.+) casualty\n                Interval: (.+)s\n                Bulk(.+)$/, '自动购买致死性维度$1(已达上限)\n                消耗: $2受害者\n                间隔: $3秒\n                数量$4'],
    [/^Autobuys Fatality Dimension (\d+).\n                Cost: (.+) casualty\n                Interval: (.+)s\n                Bulk(.+)$/, '自动购买致死性维度$1\n                消耗: $2受害者\n                间隔: $3秒\n                数量$4'],
    [/^Autobuys Fatality Dimension Multiplier.\(MAXED\)\n                Cost: (.+) casualty\n                Interval: (.+)s\n                Bulk(.+)$/, '自动购买致死性维度倍增器(已达上限)\n                消耗: $1受害者\n                间隔: $2秒\n                数量$3'],
    [/^Autobuys Fatality Dimension Boost.\(MAXED\)\n                Cost: (.+) casualty\n                Interval$/, '自动购买致死性维度加成(已达上限)\n                消耗: $1受害者\n                间隔'],
    [/^Autobuys Fatality Multiplier Boost.\(MAXED\)\n                Cost: (.+) casualty\n                Interval$/, '自动购买致死性倍增器加成(已达上限)\n                消耗: $1受害者\n                间隔'],
    [/^Automatically Sacrifice at 100x.\(MAXED\)\n                Cost: (.+) casualty\n                Interval$/, '献祭倍率到达100×时自动献祭(已达上限)\n                消耗: $1受害者\n                间隔'],
    [/^Automatically Sacrifice at 100x.\n                Cost: (.+) casualty\n                Interval$/, '献祭倍率到达100×时自动献祭\n                消耗: $1受害者\n                间隔'],
    [/^Autobuys Fatality Multiplier Boost.\n                Cost: (.+) casualty\n                Interval$/, '自动购买致死性倍增器加成\n                消耗: $1受害者\n                间隔'],
    [/^Autobuys Fatality Dimension Boost.\n                Cost: (.+) casualty\n                Interval$/, '自动购买致死性维度加成\n                消耗: $1受害者\n                间隔'],
    [/^Autobuys Fatality Dimension Multiplier.\n                Cost: (.+) casualty\n                Interval: (.+)s\n                Bulk(.+)$/, '自动购买致死性维度倍增器\n                消耗: $1受害者\n                间隔: $2秒\n                数量$3'],
    [/^Produces Casualty Dimension (\d+).\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount(.+)$/, '生产受害者维度$1\n                消耗: $2受害者\n                倍数: $3×\n                数量$4'],
    [/^Produces casualty power.\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount(.+)$/, '生产受害者力量\n                消耗: $1受害者\n                倍数: $2×\n                数量$3'],
    [/^Produces Casualty Dimension (\d+).\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount$/, '生产受害者维度$1\n                消耗: $2受害者\n                倍数: $3×\n                数量'],
    [/^Produces casualty power.\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount$/, '生产受害者力量\n                消耗: $1受害者\n                倍数: $2×\n                数量'],
    [/^Increase the replicate multiplier.\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount$/, '增加复制倍增器\n                消耗: $1受害者\n                倍数: $2×\n                数量'],
    [/^Increase the replicate multiplier.\n                Cost: (.+) casualty\n                Multiplier: (.+)x\n                Amount(.+)$/, '增加复制倍增器\n                消耗: $1受害者\n                倍数: $2×\n                数量$3'],
    [/^Increase the max Replicated Boosts.\n                Cost: (.+) casualty\n                Max: (.+)\n                Amount$/, '增加最大复制加成\n                消耗: $1受害者\n                最大: $2\n                数量'],
    [/^Reduce the replicate interval.\n                Cost: (.+) casualty\n                Interval: (.+)Planck Times\n                Amount$/, '降低复制间隔\n                消耗: $1受害者\n                间隔: $2普朗克时间\n                数量'],
    [/^Reduce the replicate interval.\n                Cost: (.+) casualty\n                Interval: (.+)\n                Amount$/, '降低复制间隔\n                消耗: $1受害者\n                间隔: $2\n                数量'],
    [/^Multiply Casual Virus gain by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount$/, '受害病毒获取乘以$1\n                消耗: $2受害病毒\n                效果$3\n                数量'],
    [/^Increase Casual Virus gain exponent by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount(.+)$/, '受害病毒获取指数增加$1\n                消耗: $2受害病毒\n                效果$3\n                数量$4'],
    [/^Raise \'Self Casual Boost\' to(.+)based on Casual Viruses\).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount(.+)$/, '提高"自身受害加成"$1基于受害病毒)\n                消耗: $2受害病毒\n                效果$3\n                数量$4'],
    [/^Raise \'Self Casual Boost\' to(.+)based on Casual Viruses\).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount$/, '提高"自身受害加成"$1基于受害病毒)\n                消耗: $2受害病毒\n                效果$3\n                数量'],
    [/^Increase Casual Virus gain exponent by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\(softcapped\)\n                Amount(.+)$/, '受害病毒获取指数增加$1\n                消耗: $2受害病毒\n                效果$3(已达软上限)\n                数量$4'],
    [/^Increase Casual Virus gain exponent by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\(softcapped\)\n                Amount$/, '受害病毒获取指数增加$1\n                消耗: $2受害病毒\n                效果$3(已达软上限)\n                数量'],
    [/^Multiply Casual Virus gain by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount(.+)$/, '受害病毒获取乘以$1\n                消耗: $2受害病毒\n                效果$3\n                数量$4'],
    [/^Multiply Casual Virus gain by(.+).\n                Cost: (.+) casual viruses\n                Effect(.+)\n                Amount$/, '受害病毒获取乘以$1\n                消耗: $2受害病毒\n                效果$3\n                数量'],
    [/^Divide immunity by (.+).\n                Cost(.+) infection power\n                Effect(.+) \(softcapped\)\n                Amount$/, '降低免疫$1\n                消耗$2感染力量\n                效果$3(已达软上限)\n                数量'],
    [/^Divide immunity by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '降低免疫$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Divide immunity by (.+).\n                Cost(.+) infection power\n                Effect(.+) \(softcapped\)\n                Amount(.+)$/, '降低免疫$1\n                消耗$2感染力量\n                效果$3(已达软上限)\n                数量$4'],
    [/^Divide immunity by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '降低免疫$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Increase \'Immunity Divider\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '增加"免疫降低"基础$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Increase \'Immunity Divider\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '增加"免疫降低"基础$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Increase \'Infecter Base\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '增加"感染者基础"基础$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Increase \'Infecter Base\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '增加"感染者基础"基础$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Increase \'Power Gain\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '增加"力量获取"基础$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Increase \'Power Gain\' base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '增加"力量获取"基础$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Multiply infecter base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '感染者基础乘以$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Multiply infecter base by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '感染者基础乘以$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Multiply infection power gain by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '感染力量获取基础乘以$1\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Multiply infection power gain by (.+).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount(.+)$/, '感染力量获取基础乘以$1\n                消耗$2感染力量\n                效果$3\n                数量$4'],
    [/^Multiply max buyable level by (.+)based on UC\).\n                Cost(.+) infection power\n                Effect(.+)\n                Amount$/, '最大购买项等级乘以$1基于反防疫病例)\n                消耗$2感染力量\n                效果$3\n                数量'],
    [/^Multiply and raise \'Disease Gain\' base by 1.025.\n                Cost(.+) infectious diseases\n                Effect(.+)\n                Amount(.+)$/, '"疾病获取"的基础同时乘以和提高1.025\n                消耗$1感染性疾病\n                效果$2\n                数量$3'],
    [/^Multiply and raise \'Disease Gain\' base by 1.025.\n                Cost(.+) infectious diseases\n                Effect(.+)\n                Amount$/, '"疾病获取"的基础同时乘以和提高1.025\n                消耗$1感染性疾病\n                效果$2\n                数量'],
    [/^Multiply and raise base disease gain by (.+).\n                Cost(.+) infectious diseases\n                Effect(.+)\n                Amount$/, '疾病获取基础同时乘以和提高$1\n                消耗$2感染性疾病\n                效果$3\n                数量'],
    [/^Multiply and raise base disease gain by (.+).\n                Cost(.+) infectious diseases\n                Effect(.+)\n                Amount(.+)$/, '疾病获取基础同时乘以和提高$1\n                消耗$2感染性疾病\n                效果$3\n                数量$4'],
    [/^Multiply UI gain by (.+).\n                Cost(.+) Unquarantined Cases\n                Multiplier(.+)\n                Amount(.+)$/, '反防疫感染获取乘以$1\n                消耗$2反防疫病例\n                倍数$3\n                数量$4'],
    [/^Multiply UI gain by (.+).\n                Cost(.+) Unquarantined Cases\n                Multiplier(.+)\n                Amount$/, '反防疫感染获取乘以$1\n                消耗$2反防疫病例\n                倍数$3\n                数量'],
    [/^Multiply UC gain by (.+).\n                Cost(.+) Unquarantined Cases\n                Multiplier(.+)\n                Amount(.+)$/, '反防疫病例获取乘以$1\n                消耗$2反防疫病例\n                倍数$3\n                数量$4'],
    [/^Multiply UC gain by (.+).\n                Cost(.+) Unquarantined Cases\n                Multiplier(.+)\n                Amount$/, '反防疫病例获取乘以$1\n                消耗$2反防疫病例\n                倍数$3\n                数量'],
    [/^Increase UI to UC exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount(.+)$/, '反防疫感染生产反防疫病例的指数增加$1\n                消耗$2反防疫病例\n                效果$3\n                数量$4'],
    [/^Increase UI to UC exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount$/, '反防疫感染生产反防疫病例的指数增加$1\n                消耗$2反防疫病例\n                效果$3\n                数量'],
    [/^Increase UI gain exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount(.+)$/, '反防疫感染的指数增加$1\n                消耗$2反防疫病例\n                效果$3\n                数量$4'],
    [/^Increase UI gain exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount$/, '反防疫感染的指数增加$1\n                消耗$2反防疫病例\n                效果$3\n                数量'],
    [/^Multiply Quarantine exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount(.+)$/, '防疫的指数乘以$1\n                消耗$2反防疫病例\n                效果$3\n                数量$4'],
    [/^Multiply Quarantine exponent by (.+).\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount$/, '防疫的指数乘以$1\n                消耗$2反防疫病例\n                效果$3\n                数量'],
    [/^Multiply \'Cases Boost\' base by (.+) and get 1 free UC Boost, UI Boost, and Quarantine Boost.\n                Cost(.+) Unquarantined Cases\n                Effect(.+)\n                Amount$/, '"病例加成"基础乘以$1并获得额外1个反防疫病例加成、反防疫感染加成和防疫加成\n                消耗$2反防疫病例\n                效果$3\n                数量'],
    [/^Increase \'Immunity Divider\' base by (.+).\n      $/, '增加"免疫降低"基础$1\n      '],
    [/^Increase \'Infecter Base\' base by (.+).\n      $/, '增加"感染者基础"基础$1\n      '],
    [/^Increase \'Power Gain\' base by (.+).\n      $/, '增加"力量获取"基础$1\n      '],
    [/^Multiply Fatality Dimension 8 by (.+).$/, '致命性维度8乘以$1'],
    [/^Starting a challenge does a casualty reset. Completing a challenge gives (.+) casualty$/, '开始挑战将进行一次受害者重置，完成一个挑战可以获得$1受害者'],
    [/^Multiplier: (.+)$/, '倍数：$1'],
    [/^infectious diseases per second \(starts at (.+) infection power$/, '感染性疾病每秒(开始于$1感染力量'],
    [/^severity and (.+) recoveries per second.$/, '严重性和$1恢复每秒'],
    [/^You have (.+) recoveries, which divides severity gain by (.+)$/, '你有$1恢复，会降低严重性获取$2'],
    [/^You have made a total of (.+) deaths$/, '你总共获得了$1死亡'],
    [/^You have made a total of (.+) virus points$/, '你总共获得了$1病毒点数'],
    [/^You have made a total of (.+) infectivity$/, '你总共获得了$1传染'],
    [/^You have made a total of (.+) replicators$/, '你总共获得了$1复制'],
    [/^You have made a total of (.+) uncoaters$/, '你总共获得了$1脱壳者'],
    [/^You have made a total of (.+) fatality$/, '你总共获得了$1致死性'],
    [/^You have made a total of (.+) casualty.$/, '你总共获得了$1受害者'],
    [/^You are gaining (.+) fatality power per second.$/, '你获得$1致死性力量每秒'],
    [/^You are gaining (.+) Fatality Dimension (\d+) per second.$/, '你获得$1致死性维度$2每秒'],
    [/^You are gaining (.+) Casualty Dimension (\d+) per second.$/, '你获得$1受害者维度$2每秒'],
    [/^You are gaining (.+) casualty power per second.$/, '你获得$1受害者力量每秒'],
    [/^Last save was (.+)s ago. Average TPS = (.+)s\/tick.$/, '上次保存在$1秒之前，平均速度=$2秒/刻'],
    [/^(.+) \/ (.+) cases		\n		$/, '$1/$2病例		\n		'],
    [/^(.+) \/ (.+) infectivity		\n		$/, '$1/$2传染		\n		'],
    [/^(.+)x to replicators base, (.+)x to uncoaters base.$/, '$1×复制,$2×脱壳者'],
    [/^(.+)\/sec$/, '$1/秒'],
    [/^(.+) \/ (.+) uncoaters		\n		$/, '$1 / $2 脱壳者		\n		'],
    [/^Replicated Boosts: (.+)\/$/, '复制加成: $1/'],
    [/^(.+) total deaths$/, '$1 总死亡'],
    [/^(\d+).(\d+)e(\d+) cases$/, '$1.$2e$3 病例'],
    [/^(\d+).(\d+)e(\d+),(\d+) cases$/, '$1.$2e$3,$4 病例'],
    [/^(\d+).(\d+)e(\d+),(\d+),(\d+) cases$/, '$1.$2e$3,$4,$5 病例'],
    [/^(\d+) infecters$/, '$1 感染者'],
    [/^(\d+),(\d+) infecters$/, '$1,$2 感染者'],
    [/^(\d+),(\d+),(\d+) infecters$/, '$1,$2,$3 感染者'],
    [/^(.+) total fatality$/, '$1 总致死性'],
    [/^(.+) total casualty$/, '$1 总受害者'],
    [/^(.+) \(softcapped$/, '$1 (已达软上限'],
    [/^(.+) fatality$/, '$1 致死性'],
    [/^(.+) cases per second$/, '$1 病例每秒'],
    [/^You have (.+) cases$/, '你有$1病例'],
    [/^Challenge Points:(.+)$/, '挑战点数:$1'],
    [/^You have (.+) infectivity$/, '你有$1传染'],
    [/^You have (.+) severity$/, '你有$1严重性'],
    [/^You have (.+) deaths$/, '你有$1死亡'],
    [/^Next at (.+)$/, '下一点需要$1'],
    [/^\^(.+),$/, '^$1,'],
    [/^Fatally:(.+)\(hardcapped\), Cases:(.+)$/, '致死性:$1(已达硬上限),病例:$2'],
    [/^Fatally:(.+), Cases:(.+)$/, '致死性:$1,病例:$2'],

]);