/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //短语
    '			A\n		': '			成就\n		',
    '			D\n		': '			死亡\n		',
    '			V\n		': '			病毒\n		',
    '			I\n		': '			传染\n		',
    '			R\n		': '			复制\n		',
    '			S\n		': '			症状\n		',
    '			ST\n		': '			统计\n		',
    '			IN\n		': '			感染者\n		',
    '			U\n		': '			脱壳\n		',
    '			F\n		': '			致死性\n		',
    'virus points': '病毒点数',
    'Currently': '当前',
    'Keep Going': '继续',
    'infectivity': '传染',
    '15 total infectivity': '15总传染',
    '2,000 total infectivity': '2,000总传染',
    '\(softcapped': '(已达软上限',
    'replicators': '复制',
    '5 replicators': '5复制',
    '12 replicators': '12复制',
    'Reset for \+': '重置获得+',
    'uncoaters': '脱壳者',
    'ON': '开',
    'OFF': '关',
    'Completed': '已完成',
    '				Goal:': '				目标:',
    '				Reward': '				奖励',
    'symptoms': '症状',
    'deaths': '死亡',
    'fatality': '致死性',
    'Achievements': '成就',
    'Achievement Points': '成就点',
    'Atomic Virus': '原子病毒',
    'Auto': '自动',
    'Automated': '自动化',
    'Automatic Diseases': '自动化疾病',
    'Infect': '感染',
    'Thousand Infected': '千人感染',
    'Million Infected': '百万感染',
    'Covid': '冠状病毒',
    'World Infected': '世界级感染',
    'Infected infections': '传染性感染',
    'Upgraded infections': '传染性升级',
    'Replicated': '复制',
    'Infected company': '感染工厂',
    'SUS Upgrade': '极易感升级',
    'Uncoated': '脱壳',
    'softcapped': '已达软上限',
    'hardcapped': '已达硬上限',
    'Challenging': '挑战中',
    'Infinite infections': '无限感染',
    'Severe case': '严重病例',
    'Dead': '死',
    'Corona Death': '死亡日冕',
    'Coffin': '棺材',
    'Coffin Dance': '棺材之舞',
    'Coughin Dance': '咳嗽之舞',
    'Mortal Kombat': '致命格斗',
    'Kortal Mombat': '斗格命致',
    'DIMENSIONS\?\?': '维度??',
    'NG\+\+\+ INFECTED': 'NG+++感染',
    'PPOOWWEERR!': '力！量！',
    'The 9th Dimension is a lie': '第九维度是个谎言',
    'Casual': '受害',
    'Fatally Challenged': '致命的挑战',
    'Zero Deaths': '零死亡',
    'REPLICANTI': '反复制',
    '\'ZERO\' Deaths': '"零"死亡',
    '0 cases from Casualty': '受害者0病例',
    'GoogolPlex': '古戈尔',
    'When will it be enough\?': '什么时候才够?',
    'Corona GAS': '日冕GAS',
    'Infected Challenge': '感染挑战',
    'Unimmune': '非免疫',
    'Diseased Diseases': '病态疾病',
    'Quarantined': '隔离',
    'E\-World Quarantine': '全世界隔离',
    'Unquarantined Quarantine': '未隔离隔离',
    'Multi\-Million': '百万倍增',
    'Cased GAS': '病例级GAS',
    'Molecular Virus': '分子病毒',
    'Phospate': '磷酸酯',
    'Phospate Virus': '磷酸酯病毒',
    'mRNA Virus': 'mRNA病毒',
    'Corona GAS GAS': '日冕GAS GAS',
    'Mutated': '突变',
    'Infecterrr': '感感感染',
    'In\'F\'ected': '感F染',
    'Mutated Mutations': '突变型突变',
    'fatality power': '致死性力量',
    'Max All \(M': '购买最大(M',
    'Fatality Dimension': '致死性维度',
    'Fatality Dimension Boost': '致死性维度加成',
    'Fatality Dimension Multiplier': '致死性维度倍增器',
    'Social Distant Multiplier Boost': '远距离倍增器加成',
    '': '',
    '': '',
    
    //长句
    'Gain 0.1 cases\/s.': '获得0.1病例/秒',
    'Your best virus points is ee': '你的最高病毒点数为ee',
    'Your best virus points is e': '你的最高病毒点数为e',
    'Your best virus points is': '你的最高病毒点数为',
    'Multiply cases gain.': '病例获取加成',
    'Multiplier to cases based on VP.': '基于病毒点数加成病例获取',
    'Multiplier to VP based on VP.': '基于病毒点数加成病毒点数获取',
    'Multiplier to cases based on cases.': '基于病例加成病例获取',
    'Multiplier to VP based on cases.': '基于病例加成病毒点数获取',
    'Raise \'Infection\' to the number of bought upgrades.': '基于已购买升级数加成"感染"',
    '\'Self Boost\' is stronger based on VP.': '基于病毒点数加成"自身加成"',
    '\'Contaminate\' is stronger based on cases.': '基于病例加成"污染"',
    'which boost cases gain by': '加成你的病例获取',
    'Your best infectivity is ee': '你的最高传染为ee',
    'Your best infectivity is e': '你的最高传染为e',
    'Your best infectivity is': '你的最高传染为',
    'Keep virus upgrades on reset.': '重置时保留病毒升级',
    'Gain 100% of VP gain per second.': '每秒获得100%重置可以获得的病毒点数',
    'Infectivity boosts VP gain.': '基于传染加成病毒点数',
    'Infectivity boosts \'Transmission\'.': '基于传染加成"传播"',
    'Multiplier to infectivity based on VP.': '基于病毒点数加成传染',
    'Infectivity increases \'Infection\' base.': '基于传染加成"感染"基础',
    'Cases increase \'Infection\' base.': '基于病例加成"感染"基础',
    'Multiplier to infectivity based on cases.': '基于病例加成传染',
    '\'Susceptible\' is stronger based on replicators and make it add and multiply.': '复制加成"易感"且同时加和乘',
    '\'Drug Resistance\' is stronger based on replicators and make it add and multiply.': '复制加成"药物抗性"且同时加和乘',
    '\'Resistance\' and \'Environmental Hardening\' is stronger based on infectivity.': '基于复制加成"抗性"和"环境强化"',
    'and increasing \'Infection\' base by': '并加成"感染"基础',
    'Your best replicators is e': '你的最高复制是e',
    'Your best replicators is': '你的最高复制是',
    'Infectivity boosts replicators 1st effect base.': '基于传染加成复制的第一个效果',
    'Replicators boost \'Disease\'.': '基于复制加成"疾病"',
    'VP boosts replicators 1st effect base.': '基于病毒点数加成复制的第一个效果',
    'VP boosts replicators 2nd effect.': '基于病毒点数加成复制的第二个效果',
    'Cases boost \'More Infections\'.': '基于病例加成"更多感染"',
    '\'Self Boost\' is stronger based on replicators': '基于复制加成“自身加成”',
    '\'Contaminate\' is stronger based on replicators': '基于复制加成"污染"',
    'Unlock a row of infectivity upgrades.': '解锁一排传染升级',
    '\'DNA\' is stronger based on cases': '基于病例加成"DNA"',
    'You can buy max replicators.': '购买复制可以购买最大',
    'which boost cases and infectivity by': '可以加成病例和传染',
    ', and boosts \'Uncoating\' by': ',且加成"脱壳"',
    'Your best uncoaters is e': '你的最高脱壳者为e',
    'Your best uncoaters is': '你的最高脱壳者为',
    'Best uncoaters boosts \'Infection\' base.': '基于最高脱壳者加成"感染"',
    '\'Transmission\' softcap starts later based on uncoaters and replicators.': '基于脱壳者和复制延缓"传播"软上限',
    'Uncoaters and replicators boost each other .': '脱壳者和复制互加',
    'Cases make replicators cheaper.': '基于病例降低复制价格',
    'Remove \'Air Transmission\' hardcap and its softcap starts later based on cases.': '移除"空气传播"硬上限，基于病例延缓它的软上限',
    'Infectivity boosts replicators 2nd effect.': '基于传染加成复制的第二个效果',
    'Infectivity boosts uncoaters 2nd effect.': '基于传染加成脱壳者的第二个效果',
    '\'Transcription\' is stronger based on uncoaters.': '基于脱壳者加成"转录"',
    'Keep Infectivity\/Replicator milestones on reset.': '重置保留传染/复制里程碑',
    'Gain 100% of infectivity gain per second.': '每秒获得重置可获得100%传染',
    'Keep Infectivity\/Replicator upgrades on reset.': '重置保留传染/复制升级',
    'Autobuy replicators.': '自动购买复制',
    'Replicators reset nothing.': '复制不再重置任何东西',
    'Unlock uncoater challenges.': '解锁脱壳者挑战',
    'Uncoaters are useless.': '脱壳者没有效果',
    'Uncoaters are useless. \(Completed': '脱壳者没有效果(已完成',
    'Infectivity and \'Infection\' are useless.': '传染和"感染"没有效果',
    'Infectivity and \'Infection\' are useless. \(Completed': '传染和"感染"没有效果(已完成',
    'Replicators are useless.': '复制没有效果',
    'Replicators are useless. \(Completed': '复制没有效果(已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4\) \(Completed': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4)(已完成',
    '\'Transmission\' softcap starts instantly and \'Coated\' and \'Disinfectant\' are applied at once. Cases gain is multiplied by 5\^\(total challenge completions-4': '"传播"软上限立即开始且"已脱壳"和"无法传染"同时生效，病例获取乘以5^(总挑战完成数-4',
    'Cases boost \'Genetic ReShuffle\'.': '基于病例加成"基因重组"',
    'Infectivity makes uncoaters cheaper.': '基于传染降低脱壳者价格',
    'Cases boost replicators 1st effect base.': '基于病例加成复制的第一个加成',
    'VP boosts \'Transcription\' and makes \'Transmission\' softcap weaker.': '基于病毒点数加成"感染"且使"感染"的软上限更弱',
    'which produces': '可以产生',
    'severity  \(softcapped\)  per second.': '严重性(已达软上限)每秒',
    'severity per second.': '严重性每秒',
    'You have': '你有',
    'severity, which boosts cases, VP, and infectivity by': '严重性，加成病例、病毒点数和传染',
    'Severity boosts uncoaters 1st effect base.': '基于严重性加成脱壳者的第一个加成',
    'Uncoaters 2nd effect is boosted by bought symptom upgrades.': '基于已购买的症状升级数加成脱壳者的第二个加成',
    'Symptoms boost uncoaters 1st effect base.': '基于症状加成脱壳者的第一个加成',
    'Infectivity boost severity gain.': '基于传染加成严重性获取',
    'Severity boosts replicators 1st effect base.': '基于严重性加成复制的第一个加成',
    '\'Fever\' boosts severity effect.': '基于"发热"加成严重性效果',
    '\'Infectivity Gain\' gives free levels to \'Severity Gain\'.': '"传染获取"会提供额外的"严重性获取"等级',
    '\'Symptom Base\' gives free levels to \'Severity Gain\'.': '"症状基础"会提供额外的"严重性获取"等级',
    'Symptoms boost \'Infection\' base.': '基于症状加成"感染"',
    '\'Uncoater Base\' gives free levels to \'Infectivity Gain\'.': '"脱壳者基础"会提供额外的"传染获取"等级',
    '\'Uncoater Base\' gives free levels to \'Symptom Base\' and autobuy buyables once per second.': '"脱壳者基础"会提供额外的"症状基础"等级且每秒自动购买购买项',
    'Replicators boost severity gain.': '基于复制加成严重性获取',
    '\'Severity Gain\' base is increased by 0.0002 per level.': '"严重性获取"每级增加基础0.0002',
    '\'Coated Boost\' gives free \'Infectivity gain\'.': '"已脱壳加成"会提供额外的"传染获取"等级',
    'Cases boost symptom base.': '基于病例加成症状',
    'Deaths reduce \'Coated Boost\' scaling base.': '基于死亡降低"已脱壳加成"涨价速度',
    'Severity reduces \'Uncoater Base\' scaling base.': '基于严重性降低"脱壳者基础"涨价速度',
    'Cases reduce \'Infection Base\' scaling base.': '基于病例降低"感染基础"涨价速度',
    '\'Infection Base\' gives free \'Coated Boost\' and \'Uncoater Base\'.': '"感染基础"会提供额外的"已脱壳加成"和"脱壳者基础"等级',
    'Each \'Infection Base\' adds 0.0001 to \'Symptom Base\' base.': '每个"感染基础"会增加"症状基础"的基础0.0001',
    'Cases boost severity effect.': '基于病例加成严重性效果',
    'Infectivity boosts \'Deadly\'.': '基于传染加成"致死性"',
    'Uncoaters boost severity gain exponent.': '基于脱壳者加成严重性获取指数',
    'Replicators boost severity gain exponent.': '基于复制加成严重性获取指数',
    'Severity boosts \'Transmission\', \'Smell Loss\' buys 25x more, and unlock a row of death upgrades.': '基于严重性加成"传播"，"嗅觉丧失"购买量25×，解锁一排死亡升级',
    'Unlock buyables.': '解锁购买项',
    'Unlock 2 more buyables.': '解锁两个额外的购买项',
    'Symptoms and severity are useless. Cases gain is \^0.1. \(Completed': '症状和严重性没有效果，病例获取^0.1 (已完成',
    'Symptoms and severity are useless. Cases gain is \^0.1.': '症状和严重性没有效果，病例获取^0.1',
    'Symptom buyables are useless. Cases gain is \^0.01. \(Completed': '症状购买项没有效果，病例获取^0.01 (已完成',
    'Symptom buyables are useless. Cases gain is \^0.01.': '症状购买项没有效果，病例获取^0.01',
    'Row 3 Upgrades are useless. Cases gain is \^0.03. \(Completed': '第三排升级没有效果，病例获取^0.03 (已完成',
    'Row 3 Upgrades are useless. Cases gain is \^0.03.': '第三排升级没有效果，病例获取^0.03',
    '\'Asymptomatic\' and \'Unbuyable\' at once. \(Completed': '同时进行"无症状"和"无购买项" (已完成',
    '\'Asymptomatic\' and \'Unbuyable\' at once.': '同时进行"无症状"和"无购买项"',
    'Cases boost severity gain.': '基于病例加成严重性获取',
    'Infectivity boosts death gain.': '基于感染加成死亡获取',
    'Deaths boost \'Discoloration\'.': '基于死亡加成"变色"',
    'Severity boosts severity gain.': '基于严重性加成严重性获取',
    'which boost cases, VP, infectivity, and severity gain by': '可以加成病例、病毒点数、传染和严重性获取',
    '\(based on best\).': '(基于最高)',
    'You are gaining': '你获得',
    'deaths per second': '死亡每秒',
    'Your best deaths is ee': '你的最高死亡为ee',
    'Your best deaths is e': '你的最高死亡为e',
    'Your best deaths is': '你的最高死亡为',
    'Deaths reset all previous progress.': '死亡会重置前面所有进度',
    'Deaths boosts symptom base.': '基于死亡加成症状',
    'Cases boost death gain.': '基于病例加成死亡获取',
    'Deaths boost \'Infectivity Gain\' base.': '基于死亡加成"传染获取"',
    'Deaths boost \'Transmission\'.': '基于死亡加成"传播"',
    'Deaths boost uncoater base.': '基于死亡加成脱壳者',
    'Double death gain per death upgrade bought.': '每个死亡升级使死亡获取翻倍',
    '\'Smell Loss\' buys 2x more.': '"嗅觉丧失"购买量2×',
    'Severity boosts death gain.': '基于严重性加成死亡获取',
    'Deaths boost severity gain.': '基于死亡加成严重性获取',
    'Cases boost severity gain and \'Smell Loss\' buys 5x more.': '基于病例加成严重性获取且"嗅觉丧失"购买量5×',
    'VP boost \'Fatal\' and \'Smell Loss\' buys 2x more and 2x often.': '基于病毒点数加成"致命"且"嗅觉丧失"购买量和频率2x',
    'Bought death upgrades boost \'Fever\' and unlock more symptom upgrades.': '基于已购买死亡升级加成"发热"并解锁更多症状升级',
    'Deaths make symptom scaling start later.': '基于死亡延缓症状涨价',
    'Stop gaining recoveries and upgrades that reduce recovery effect boost severity gain.': '停止获得恢复和降低恢复效果提高严重性获取的升级',
    'Deaths boost cases gain.': '基于死亡加成病例获取',
    'Deaths boost severity gain exponent.': '基于死亡加成严重性指数',
    'Keep uncoater\/symptom milestones on reset.': '重置保留脱壳者/症状里程碑',
    'You can buy max uncoaters.': '脱壳者可以购买最大',
    'Autobuy uncoaters and unlock upgrades.': '自动购买脱壳者并解锁升级',
    'Keep uncoater challenge completions.': '保留脱壳者挑战进度',
    '\'Smell Loss\' buys 10x more and buyables cost nothing.': '"嗅觉丧失"购买量10×且购买无消耗',
    'Uncoaters reset nothing.': '脱壳者不再重置任何东西',
    'Keep previous upgrades on reset.': '重置保留前面的升级',
    'Autobuy symptoms.': '自动购买症状',
    'Unlock symptom challenges.': '解锁症状挑战',
    'Symptoms reset nothing and \'Smell Loss\' buys 2x often.': '症状不再重置任何东西且"嗅觉丧失"购买频率2×',
    'Gain 1% of death gain per second and disable prestige.': '每秒获得重置可获得的1%死亡且禁用死亡重置',
    'Buyables give free levels to the previous layer buyable.': '购买项会使前面层级的购买项获得额外等级',
    'which boost cases, VP, infectivity, severity by': '可以加成病例、病毒点数、传染和严重性',
    ', and death gain by': '，并且死亡获取提高',
    'fatality per second': '致死性每秒',
    'Your best fatality is e': '你的最高致死性为e',
    'Your best fatality is': '你的最高致死性为',
    'Keep first 5 death milestones on reset.': '重置保留前五个死亡里程碑',
    'Keep next 6 death milestones on reset.': '重置保留接下来的六个死亡里程碑',
    'Keep symptom challenges on reset.': '重置保留症状挑战进度',
    'Unlock death buyables.': '解锁死亡购买项',
    'Unlock fatality dimensions and death buyables cost nothing.': '解锁致死维度且死亡购买项无消耗',
    'Gain 1% of fatality gain per second.': '每秒获得重置可获得的1%致死性',
    'Unlock Dimension Multiplier and autobuyers buy 100x more.': '解锁维度倍增器且自动购买者购买量100x',
    'Gain 100% of fatality gain per second and disable prestige.': '每秒获得重置可获得的100%致死性并禁用重置',
    'Unlock Dimension Shifts and dimensions cost nothing.': '解锁维度转换且维度无消耗',
    'Unlock Multiplier Boosts and buy max Dimension Boosts.': '解锁倍增器加成和最大购买维度加成',
    'Unlock Casualty and buy max Multiplier Boosts.': '解锁受害者和最大购买倍增器加成',
    'Multiplier Boosts don\'t reset Dimension Boosts and unlock Auto Sacrifice.': '倍增器加成不再重置维度加成，解锁自动献祭',
    'Dimension Boosts and Sacrifice reset nothing.': '维度加成和献祭不再重置任何东西',
    'Multiplier Boosts reset nothing.': '倍增器加成不再重置任何东西',
    'Unlock Casualty Dimensions.': '解锁受害者维度',
    'Unlock Casuals.': '解锁受害',
    'Gain 1% of casualty gain per second, autobuy Casualty Multiplier, Casualty Multiplier costs nothing, and disable prestige.': '每秒获得重置可获得的1%受害者，自动购买受害者倍增器且无消耗，禁用受害者重置',
    'Autobuy Casualty Dimensions and they cost nothing.': '自动购买受害者维度且无消耗',
    'Unlock Casual Virus and Replicated Boost Autobuyer.': '解锁受害病毒和复制加成自动购买者',
    'Unlock Casual Virus buyables.': '解锁受害病毒购买项',
    'Symptoms boost severity after softcap at reduced effect.': '症状在软上限之后对严重性仍有较低加成',
    'Deaths boost fatality gain.': '基于死亡加成致命性获取',
    '\'Asymptomatic\' reward is applied after softcap at reduced effect.': '"无症状"在软上限之后仍有较低加成',
    'Cases boost fatality gain.': '基于病例加成致死性获取',
    'Fatality 1st effect is applied after softcap and is stronger based on deaths.': '基于死亡加成致死性第一项加成且在软上限之后仍有较低加成',
    'Fatality boosts severity gain exponent and unlock 3 more symptom buyables.': '基于致死性加成严重性指数并解锁三个症状购买项',
    'Severity boosts fatality gain.': '基于严重性加成致死性获取',
    'Fatality boosts death gain.': '基于致死性加成死亡获取',
    'Infectivity boosts fatality gain.': '基于传染加成致死性获取',
    'Add 1 to base fatality gain exponent and autobuy death buyables 100 per second.': '致死性基础指数+1且每秒自动购买100个死亡购买项',
    'Infectivity boosts \'Fatal\'.': '基于传染加成"致命"',
    'Cases add to the fatality exponent.': '基于病例加成致命性指数',
    'Fatality power boosts \'Infection\'.': '基于致死性力量加成"感染"',
    'Fatality boosts fatality power gain.': '基于致死性加成致死性获取',
    'Deaths boost fatality dimensions.': '基于死亡加成致死性维度',
    'Cases boost fatality dimensions.': '基于病例加成致死性维度',
    'Fatality power boosts fatality exponent.': '基于致死性力量加成致死性指数',
    'Fatality power boosts cases gain.': '基于致死性力量加成病例获取',
    'Fatality boosts cases gain.': '基于致死性加成病例获取',
    'Fatality power boosts death gain.': '基于致死性力量加成死亡获取',
    'Deaths add to the fatality exponent.': '基于死亡增加致死性指数',
    'Severity boosts fatality dimensions.': '基于严重性加成致死性维度',
    'Infectivity increases multiplier per dimension.': '基于传染增加每个维度的倍率',
    'Fatality boosts uncoaters 1st effect.': '基于致死性加成脱壳者第一项加成',
    'Uncoaters boost fatality dimensions.': '基于脱壳者加成致死性维度',
    'Replicators boost fatality dimensions.': '基于复制加成致死性维度',
    'Replicators boost fatality power effect.': '基于复制加成致死性力量效果',
    'Fatality adds to the Dimension Multiplier base.': '基于致死性增加维度倍增器基础',
    'Cases add to the Dimension Multiplier base.': '基于病例增加维度倍增器基础',
    'Reduce the Dimension and Dimension Boost cost scaling by 1.': '降低维度和维度加成膨胀速度1',
    'Fatality Dimension 8 gives 2 free \'Cases Boost\'.': '致死性第八维度额外提供2个"病例加成"',
    'Multiply the Dimension Boost base by 2.': '维度加成基础乘以2',
    'Reduce the Dimension cost scaling by 1 and autobuyers buy 1,000x more and 2x faster.': '降低维度价格膨胀速度1且自动购买者购买量1000x频率2x',
    'Reduce the Dimension Boost cost scaling by 0.5.': '降低维度加成价格膨胀0.5',
    'Multiply Dimension Boost base by 5 and Multiplier Boost is 1.125x stronger.': '维度加成基础乘5，倍增器加成乘1.125',
    'fatality power, which boosts fatality gain by': '致死性力量，可以加成致死性获取',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    
    //标题
    'Start': '开始',
    'Infection': '感染',
    'Transmission': '传播',
    'Self Boost': '自身加成',
    'Contaminate': '污染',
    'More Infections': '更多感染',
    'Disease': '疾病',
    'BOOSTER': '加成者',
    'Food Contamination': '污染食物',
    'VP Boost': '病毒点数加成',
    'Air Transmission': '空气传播',
    'Resistance': '抗性',
    'Susceptible': '易感',
    'Drug Resistance': '药物抗性',
    'Environmental Hardening': '环境强化',
    'SUSceptible': '极易感',
    'Genetic Hardening': '基因强化',
    'Genetic ReShuffle': '基因重组',
    'Replication': '复制',
    'DNA': 'DNA',
    'Attachment': '拥护',
    'Entry': '参与',
    'Uncoating': '脱壳',
    'Transcription': '转录',
    'Synthesis': '合成',
    'Virion': '病毒体',
    'Release': '释放',
    'Main': '主界面',
    'Milestones': '里程碑',
    'Challenges': '挑战',
    'Uncoated Infection': '脱壳感染',
    'Water Transmission': '水源传播',
    'Synergy': '协同',
    'Genome Replication': '基因组复制',
    'Bird Transmission': '鸟类传播',
    'Viral Proteins': '病毒蛋白',
    'Viral Enzymes': '病毒酶',
    'Endocytosis': '内吞作用',
    'Coated': '已脱壳',
    'Disinfectant': '无法传染',
    'Unreplicated': '无法复制',
    'Masks': '口罩',
    'Cough': '咳嗽',
    'Fever': '发热',
    'Tiredness': '疲劳',
    'Pain': '痛苦',
    'Sore Throat': '喉咙痛',
    'Chills': '畏寒',
    'Headache': '头痛',
    'Buyables': '购买项',
    'Diarrhea': '腹泻',
    'Conjunctivitis': '结膜炎',
    'Taste Loss': '味觉丧失',
    'Smell Loss': '嗅觉丧失',
    'Skin Rash': '皮疹',
    'Discoloration': '变色',
    'Shortness of Breath': '气短',
    'Chest Pain': '胸痛',
    'Speech Loss': '失语',
    'Movement Loss': '行动丧失',
    'Pneumonia': '肺炎',
    'Fatigue': '厌倦',
    'Congestion': '淤血',
    'Muscle Aches': '肌肉酸痛',
    'Nausea': '恶心',
    'Asthma': '哮喘',
    'Cancer': '癌症',
    'Heart Failure': '心力衰竭',
    'Severity Gain': '严重性获取',
    'Infectivity Gain': '传染获取',
    '\'Coated\' Boost': '"已脱壳"加成',
    'Symptom Base': '症状基础',
    'Uncoater Base': '脱壳者基础',
    '\'Infection\' Base': '"感染"基础',
    'Severity Boost': '严重性加成',
    'Symptom Boost': '症状加成',
    'Severity Exponent': '严重性指数',
    'Asymptomatic': '无症状',
    'Unbuyable': '无购买项',
    'Row 3 Downgrade': '第三排不升级',
    'Symptomless Symptoms': '没有症状的症状',
    'Upgrades': '升级',
    'Deadly': '死亡',
    'Fatal': '致命',
    'Lethal': '致死',
    'Blood Transmission': '血液传播',
    'Dangerous': '危险性',
    'Mortal': '必死',
    'Kill': '杀死',
    'Dying': '濒死',
    'Pass Away': '去世',
    'Perish': '消亡',
    'Expire': '逝世',
    'Decease': '亡故',
    'Demise': '终焉',
    'Murder': '谋杀',
    'Slain': '杀害',
    'Slaughter': '屠杀',
    'Death Gain': '死亡获取',
    'Distant Cases Boost': '远方病例加成',
    'Dimensions': '维度',
    'Casualty': '受害者',
    'Multiplier': '倍增器',
    'Autobuyers': '自动购买者',
    'Casualty Dimensions': '受害者维度',
    'Casuals': '受害',
    'Casual Virus': '受害病毒',
    'Lethality': '致命性',
    'Deadliness': '致命',
    'Mortality': '死亡率',
    'Fatally': '致命的',
    'Fatalness': '危险性',
    'Severely': '严重的',
    'Severer': '十分严重的',
    'Deadlier': '更致命的',
    'Infectious': '传染性',
    'More Fatal': '更多致命',
    'Fataler': '更致命',
    'Fatalest': '最致命',
    'Fatal Infection': '致命感染',
    'Powerful Fatalities': '更强的致死性',
    'Death Dimension': '死亡维度',
    'Case Dimension': '病例维度',
    'Powerful Power': '强大的力量',
    'Powerful Cases': '强大的病例',
    'Fatal Fatalities': '致死性致死',
    'Deadly Power': '死亡力量',
    'Fatal Deaths': '死亡致死',
    'Severity Dimension': '严重性维度',
    'Infected Dimension': '感染维度',
    'Uncoated Fatalities': '致死性脱壳',
    'Uncoated Dimension': '脱壳维度',
    'Replicated Dimension': '复制维度',
    'Replicated Power': '复制力量',
    'Multiplied Fatalities': '致死性倍增',
    'Multiplied Cases': '病例倍增',
    'Scaling Reduction': '降低膨胀',
    '8 Dimension Cases': '病例第八维度',
    'Boosted Boosts': '增强加成',
    'BULK': '大量',
    'Boost Scaling': '加成膨胀',
    'Boost Boosters': '加成增强者',
    'Sacrifice': '献祭',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    'Current endgame: e3.689e12 mRNA \(v0.': '当前游戏终点：e3.689e12mRNA (v0.',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(\d+) uncoaters$/, '$1 脱壳者'],
    [/^(\d+) symptoms$/, '$1 症状'],
    [/^(\d+) total death$/, '$1 总死亡'],
    [/^Completed:(\d+)\/$/, '已完成:$1/'],
    [/^Cost: (.+) virus points\n			$/, '消耗：$1病毒点数'],
    [/^Cost: (.+) replicators\n			$/, '消耗：$1复制'],
    [/^Cost: (.+) infectivity\n			$/, '消耗：$1传染'],
    [/^Cost: (.+) uncoaters\n			$/, '消耗：$1脱壳者'],
    [/^Cost: (.+) severity\n			$/, '消耗：$1严重性'],
    [/^Cost: (.+) symptoms\n			$/, '消耗：$1症状'],
    [/^Cost: (.+) fatality\n			$/, '消耗：$1致死性'],
    [/^Cost: (.+) deaths\n			$/, '消耗：$1死亡'],
    [/^\^(.+) \(softcapped$/, '^$1 (已达软上限'],
    [/^(.+)x \(softcapped$/, '$1x (已达软上限'],
    [/^Last save was (.+)s ago.$/, '上次保存在$1秒之前'],
    [/^Multiply severity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '严重性获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Multiply the uncoater base by (.+) \(based on cases\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '脱壳者基础加成$1(基于病例)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Increase \'Symptom Base\' base by (.+) \(based on fatality and severity\)\n                Cost: (.+) severity\n                Effect: \+(.+)\n                Amount: (.+)\+(.+)$/, '增加"症状基础"$1(基于致死性和严重性)\n                消耗：$2严重性\n                效果：+$3\n                数量:$4+$5'],
    [/^Multiply \'Severity Gain\' base by (.+) \(based on deaths\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '"严重性获取"基础加成$1(基于死亡)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Multiply \'Infection\' base by (.+). \(based on VP\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '"感染"基础加成$1(基于病毒点数)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Multiply the symptom base by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '症状基础加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Multiply Infectivity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)\+(.+)$/, '传染获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4+$5'],
    [/^Raise \'Coated\' reward to \^\(1\+(.+)x\) \(based on infectivity\)\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount: (.+)\+(.+)$/, '增加"已脱壳"奖励^(1+$1) (基于传染)\n                消耗：$2严重性\n                效果：^$3\n                数量:$4+$5'],
    [/^Multiply severity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '严重性获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply the uncoater base by (.+) \(based on cases\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '脱壳者基础加成$1(基于病例)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Increase \'Symptom Base\' base by (.+) \(based on fatality and severity\)\n                Cost: (.+) severity\n                Effect: \+(.+)\n                Amount: (.+)$/, '增加"症状基础"$1(基于致死性和严重性)\n                消耗：$2严重性\n                效果：+$3\n                数量:$4'],
    [/^Multiply \'Severity Gain\' base by (.+) \(based on deaths\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '"严重性获取"基础加成$1(基于死亡)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply \'Infection\' base by (.+). \(based on VP\)\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '"感染"基础加成$1(基于病毒点数)\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply the symptom base by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '症状基础加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Multiply Infectivity gain by (.+).\n                Cost: (.+) severity\n                Effect: (.+)x\n                Amount: (.+)$/, '传染获取加成$1\n                消耗：$2严重性\n                效果：$3×\n                数量:$4'],
    [/^Raise \'Coated\' reward to \^\(1\+(.+)x\) \(based on infectivity\)\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount: (.+)$/, '增加"已脱壳"奖励^(1+$1) (基于传染)\n                消耗：$2严重性\n                效果：^$3\n                数量:$4'],
    [/^Increase severity gain exponent by (.+) \(based on cases and infectivity\) and gives free levels to all previous buyables\n                Cost: (.+) severity\n                Effect: \^(.+)\n                Amount: (.+)$/, '增加严重性获取指数$1(基于病例和传染)且增加前面所有购买项的等级\n                消耗：$2严重性\n                效果：^$3\n                数量:$4'],
    [/^Multiply severity gain by (.+) after softcap \(based on deaths\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount: (.+)$/, '严重性获取加成$1在软上限之后(基于死亡)\n                消耗：$2死亡\n                效果：$3×\n                数量:$4'],
    [/^Multiply death gain by (.+) \(based on fatality\).\n                Cost: (.+) deaths\n                Effect: (.+)x\n                Amount: (.+)$/, '死亡获取加成$1(基于致死性)\n                消耗：$2死亡\n                效果：$3×\n                数量:$4'],
    [/^Raise cases gain to (.+) \(based on cases\).\n                Cost: (.+) deaths\n                Effect: \^(.+) \(softcapped\)\n                Amount: (.+)$/, '病例获取指数增加$1(基于病例)\n                消耗：$2死亡\n                效果：^$3(已达软上限)\n                数量:$4'],
    [/^Raise cases gain to (.+) \(based on cases\).\n                Cost: (.+) deaths\n                Effect: \^(.+)\n                Amount: (.+)$/, '病例获取指数增加$1(基于病例)\n                消耗：$2死亡\n                效果：^$3\n                数量:$4'],
    [/^Produces fatality power.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性力量\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 1.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度1\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 2.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度2\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 3.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度3\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 4.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度4\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 5.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度5\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 6.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度6\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Produces Fatality Dimension 7.\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '生产致死性维度7\n                消耗：$1 致死性\n                倍数：$2×\n                数量:$3('],
    [/^Multiply fatality dimensions by (.+)\n                Cost: (.+) fatality\n                Multiplier: (.+)x\n                Amount: (.+)\($/, '致死性维度乘以$1\n                消耗：$2 致死性\n                倍数：$3×\n                数量:$4('],
    [/^Multiply fatality dimensions by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount$/, '致死性维度乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量'],
    [/^Reset Dimension Boosts, and multiply Fatality Dimension Multiplier base by (.+).\n                Requires: (.+) Fatality Dimension 8\n                Multiplier: (.+)x\n                Amount: (.+)$/, '重置维度加成并使致死性维度倍增器基础乘以$1\n                需求：$2 致死性维度8\n                倍数：$3×\n                数量:$4'],
    [/^Multiply Fatality Dimension 8 by (.+).$/, '致命性维度8乘以$1'],
    [/^Multiplier: (.+)$/, '倍数：$1'],
    [/^You have (.+) cases$/, '你有$1病例'],
    [/^You have (.+) infectivity$/, '你有$1传染'],
    [/^You have (.+) severity$/, '你有$1严重性'],
    [/^You have (.+) deaths$/, '你有$1死亡'],
    [/^You have made a total of (.+) deaths$/, '你总共获得了$1死亡'],
    [/^You have made a total of (.+) virus points$/, '你总共获得了$1病毒点数'],
    [/^You have made a total of (.+) infectivity$/, '你总共获得了$1传染'],
    [/^You have made a total of (.+) replicators$/, '你总共获得了$1复制'],
    [/^You have made a total of (.+) uncoaters$/, '你总共获得了$1脱壳者'],
    [/^You have made a total of (.+) fatality$/, '你总共获得了$1致死性'],
    [/^You are gaining (.+) fatality power per second.$/, '你获得$1致死性力量每秒'],
    [/^You are gaining (.+) Fatality Dimension 1 per second.$/, '你获得$1致死性维度1每秒'],
    [/^You are gaining (.+) Fatality Dimension 2 per second.$/, '你获得$1致死性维度2每秒'],
    [/^You are gaining (.+) Fatality Dimension 3 per second.$/, '你获得$1致死性维度3每秒'],
    [/^You are gaining (.+) Fatality Dimension 4 per second.$/, '你获得$1致死性维度4每秒'],
    [/^You are gaining (.+) Fatality Dimension 5 per second.$/, '你获得$1致死性维度5每秒'],
    [/^You are gaining (.+) Fatality Dimension 6 per second.$/, '你获得$1致死性维度6每秒'],
    [/^You are gaining (.+) Fatality Dimension 7 per second.$/, '你获得$1致死性维度7每秒'],
    [/^Last save was (.+)s ago. Average TPS = (.+)s\/tick.$/, '上次保存在$1秒之前，平均速度=$2秒/刻'],
    [/^(.+) \/ (.+) cases		\n		$/, '$1/$2病例		\n		'],
    [/^(.+) \/ (.+) infectivity		\n		$/, '$1/$2传染		\n		'],
    [/^(.+)x to replicators base, (.+)x to uncoaters base.$/, '$1×复制,$2×脱壳者'],
    [/^(.+)\/sec$/, '$1/秒'],
    [/^(.+) total deaths$/, '$1 总死亡'],
    [/^(.+) total fatality$/, '$1 总致死性'],
    [/^(.+) total casualty$/, '$1 总受害者'],
    [/^(.+) \(softcapped$/, '$1 (已达软上限'],

]);